import Foundation

/// Reads and writes MakeMKV's `settings.conf` (`key = "value"` lines, `#` comments).
enum SettingsConf {
    static func parse(_ text: String) -> [String: String] {
        var out: [String: String] = [:]
        text.enumerateLines { line, _ in
            let t = line.trimmingCharacters(in: .whitespaces)
            guard !t.isEmpty, !t.hasPrefix("#"), let eq = t.firstIndex(of: "=") else { return }
            let key = t[..<eq].trimmingCharacters(in: .whitespaces)
            var value = t[t.index(after: eq)...].trimmingCharacters(in: .whitespaces)
            if value.count >= 2, value.hasPrefix("\""), value.hasSuffix("\"") {
                value = String(value.dropFirst().dropLast())
            }
            if !key.isEmpty { out[key] = value }
        }
        return out
    }

    static func serialize(_ settings: [String: String], header: String = "Written by Bromelia") -> String {
        var s = "#\n# MakeMKV settings file. \(header).\n# Changes made here are overwritten before every job.\n#\n\n"
        for key in settings.keys.sorted() {
            let v = (settings[key] ?? "").replacingOccurrences(of: "\"", with: "'").replacingOccurrences(of: "\n", with: " ")
            s += "\(key) = \"\(v)\"\n"
        }
        return s
    }
}

/// Generates MakeMKV conversion profiles (`.mmcp.xml`).
enum ProfileBuilder {
    static let makemkvDefaultSelection =
        "-sel:all,+sel:(favlang|nolang|single),-sel:(havemulti|havecore),-sel:mvcvideo,=100:all,-10:favlang"

    static func xmlEscape(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }

    static func build(_ p: GeneratedProfile, selectionOverride: String? = nil) -> String {
        let rule = selectionOverride ?? (p.selectionRule.trimmingCharacters(in: .whitespaces).isEmpty ? makemkvDefaultSelection : p.selectionRule)
        func b(_ v: Bool) -> String { v ? "true" : "false" }
        return """
        <?xml version="1.0" encoding="utf-8"?>
        <!-- Generated by Bromelia. Edit the drive configuration instead of this file. -->
        <profile>
            <name lang="eng">\(xmlEscape(p.name))</name>

            <mkvSettings
                ignoreForcedSubtitlesFlag="\(b(p.ignoreForcedSubtitlesFlag))"
                useISO639Type2T="\(b(p.useISO639Type2T))"
                setFirstAudioTrackAsDefault="\(b(p.setFirstAudioTrackAsDefault))"
                setFirstSubtitleTrackAsDefault="\(b(p.setFirstSubtitleTrackAsDefault))"
                setFirstForcedSubtitleTrackAsDefault="\(b(p.setFirstForcedSubtitleTrackAsDefault))"
                insertFirstChapter00IfMissing="\(b(p.insertFirstChapter00IfMissing))"
            />

            <profileSettings
                app_DefaultSelectionString="\(xmlEscape(rule))"
            />

            <outputSettings name="copy" outputFormat="directCopy">
                <description lang="eng">Copy track as is</description>
            </outputSettings>

            <outputSettings name="lpcm" outputFormat="LPCM-raw">
                <description lang="eng">Save as raw LPCM</description>
            </outputSettings>

            <outputSettings name="wavex" outputFormat="LPCM-wavex">
                <description lang="eng">Save as LPCM in WAV container</description>
            </outputSettings>

            <outputSettings name="flac-best" outputFormat="FLAC">
                <description lang="eng">Save as FLAC (best compression)</description>
                <extraArgs>-compression_level 12</extraArgs>
            </outputSettings>

            <outputSettings name="flac-fast" outputFormat="FLAC">
                <description lang="eng">Save as FLAC (fast compression)</description>
                <extraArgs>-compression_level 5</extraArgs>
            </outputSettings>

            <trackSettings input="default">
                <output outputSettingsName="copy"
                        defaultSelection="$app_DefaultSelectionString">
                </output>
            </trackSettings>

            <trackSettings input="LPCM-stereo">
                <output outputSettingsName="\(p.lpcmStereo.rawValue)"
                        defaultSelection="$app_DefaultSelectionString">
                </output>
            </trackSettings>

            <trackSettings input="LPCM-multi">
                <output outputSettingsName="\(p.lpcmMultichannel.rawValue)"
                        defaultSelection="$app_DefaultSelectionString">
                </output>
            </trackSettings>
        </profile>

        """
    }
}
