import BroFoundation

/// The MakeMKV conversion profile (.mmcp.xml) Bromelia generates.
public enum ProfileXml {
    /// MakeMKV's own default selection rule, used when the profile has none.
    public static let makemkvDefaultSelection = "-sel:all,+sel:(favlang|nolang|single),-sel:(havemulti|havecore),-sel:mvcvideo,=100:all,-10:favlang"

    static func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;").replacingOccurrences(of: "<", with: "&lt;").replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }

    static func track(_ input: String, _ output: String) -> String {
        "    <trackSettings input=\"\(input)\">\n"
            + "        <output outputSettingsName=\"\(escape(output))\"\n"
            + "                defaultSelection=\"$app_DefaultSelectionString\">\n"
            + "        </output>\n"
            + "    </trackSettings>\n"
    }

    /// The profile for `generated` (config-3.json's makemkv.profile.generated; missing fields take their defaults).
    public static func render(_ generated: JsonValue) -> String {
        var issues: [Issue] = []
        let g = SchemaWalker.normalize(generated, SchemaWalker.def("MakemkvProfile")["properties"]!["generated"]!, "", fill: true, &issues)
        func b(_ key: String) -> String { g[key]?.bool == true ? "true" : "false" }
        func s(_ key: String) -> String { g[key]?.string ?? "" }
        let rule = s("selectionRule").trimmingCharacters(in: .whitespaces).isEmpty ? makemkvDefaultSelection : s("selectionRule")
        var x = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        x += "<!-- Generated by Bromelia. Edit the profile in Bromelia instead of this file. -->\n"
        x += "<profile>\n"
        x += "    <name lang=\"eng\">\(escape(s("name")))</name>\n"
        x += "\n"
        x += "    <mkvSettings\n"
        for key in ["ignoreForcedSubtitlesFlag", "useISO639Type2T", "setFirstAudioTrackAsDefault", "setFirstSubtitleTrackAsDefault",
                    "setFirstForcedSubtitleTrackAsDefault", "insertFirstChapter00IfMissing"] {
            x += "        \(key)=\"\(b(key))\"\n"
        }
        x += "    />\n"
        x += "\n"
        x += "    <profileSettings\n"
        x += "        app_DefaultSelectionString=\"\(escape(rule))\"\n"
        x += "    />\n"
        x += "\n"
        let outputs = [("copy", "directCopy", "Copy track as is", nil), ("lpcm", "LPCM-raw", "Save as raw LPCM", nil),
                       ("wavex", "LPCM-wavex", "Save as LPCM in WAV container", nil),
                       ("flac-best", "FLAC", "Save as FLAC (best compression)", "-compression_level 12"),
                       ("flac-fast", "FLAC", "Save as FLAC (fast compression)", "-compression_level 5")]
        for (name, format, description, extra) in outputs {
            x += "    <outputSettings name=\"\(name)\" outputFormat=\"\(format)\">\n"
            x += "        <description lang=\"eng\">\(description)</description>\n"
            if let extra { x += "        <extraArgs>\(extra)</extraArgs>\n" }
            x += "    </outputSettings>\n"
            x += "\n"
        }
        x += track("default", "copy") + "\n" + track("LPCM-stereo", s("lpcmStereo")) + "\n" + track("LPCM-multi", s("lpcmMultichannel"))
        x += "</profile>\n"
        return x
    }
}
