using System.Text;
using System.Text.Json;
using Bromelia.Core.Config;

namespace Bromelia.Core.Logic;

/// <summary>Reads and writes MakeMKV's settings.conf format (<c>key = "value"</c>).</summary>
public static class SettingsConf
{
    public static Dictionary<string, string> Parse(string text)
    {
        var o = new Dictionary<string, string>();
        foreach (var raw in text.Split('\n'))
        {
            var t = raw.Trim();
            if (t.Length == 0 || t.StartsWith('#')) continue;
            int eq = t.IndexOf('=');
            if (eq < 0) continue;
            var key = t[..eq].Trim();
            var value = t[(eq + 1)..].Trim();
            if (value.Length >= 2 && value[0] == '"' && value[^1] == '"') value = value[1..^1];
            if (key.Length > 0) o[key] = value;
        }
        return o;
    }

    public static string Serialize(IReadOnlyDictionary<string, string> settings, string header = "Written by Bromelia")
    {
        var sb = new StringBuilder($"#\n# MakeMKV settings file. {header}.\n# Changes made here are overwritten before every job.\n#\n\n");
        foreach (var key in settings.Keys.OrderBy(k => k, StringComparer.Ordinal))
            sb.Append(key).Append(" = \"").Append(settings[key].Replace('"', '\'').Replace('\n', ' ')).Append("\"\n");
        return sb.ToString();
    }
}

/// <summary>Generates MakeMKV conversion profiles (.mmcp.xml).</summary>
public static class ProfileBuilder
{
    public const string MakemkvDefaultSelection =
        "-sel:all,+sel:(favlang|nolang|single),-sel:(havemulti|havecore),-sel:mvcvideo,=100:all,-10:favlang";

    public static string XmlEscape(string s) =>
        s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");

    public static string Build(GeneratedProfile p, string? selectionOverride = null)
    {
        var rule = selectionOverride ?? (string.IsNullOrWhiteSpace(p.SelectionRule) ? MakemkvDefaultSelection : p.SelectionRule);
        static string B(bool v) => v ? "true" : "false";
        return $"""
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Bromelia. Edit the drive configuration instead of this file. -->
<profile>
    <name lang="eng">{XmlEscape(p.Name)}</name>

    <mkvSettings
        ignoreForcedSubtitlesFlag="{B(p.IgnoreForcedSubtitlesFlag)}"
        useISO639Type2T="{B(p.UseIso639Type2T)}"
        setFirstAudioTrackAsDefault="{B(p.SetFirstAudioTrackAsDefault)}"
        setFirstSubtitleTrackAsDefault="{B(p.SetFirstSubtitleTrackAsDefault)}"
        setFirstForcedSubtitleTrackAsDefault="{B(p.SetFirstForcedSubtitleTrackAsDefault)}"
        insertFirstChapter00IfMissing="{B(p.InsertFirstChapter00IfMissing)}"
    />

    <profileSettings
        app_DefaultSelectionString="{XmlEscape(rule)}"
    />

    <outputSettings name="copy" outputFormat="directCopy">
        <description lang="eng">Copy track as is</description>
    </outputSettings>

    <outputSettings name="lpcm" outputFormat="LPCM-raw">
        <description lang="eng">Save as raw LPCM</description>
    </outputSettings>

    <outputSettings name="wavex" outputFormat="LPCM-wavex">
        <description lang="eng">Save as LPCM in WAV container</description>
    </outputSettings>

    <outputSettings name="flac-best" outputFormat="FLAC">
        <description lang="eng">Save as FLAC (best compression)</description>
        <extraArgs>-compression_level 12</extraArgs>
    </outputSettings>

    <outputSettings name="flac-fast" outputFormat="FLAC">
        <description lang="eng">Save as FLAC (fast compression)</description>
        <extraArgs>-compression_level 5</extraArgs>
    </outputSettings>

    <trackSettings input="default">
        <output outputSettingsName="copy"
                defaultSelection="$app_DefaultSelectionString">
        </output>
    </trackSettings>

    <trackSettings input="LPCM-stereo">
        <output outputSettingsName="{p.LpcmStereo.ProfileName()}"
                defaultSelection="$app_DefaultSelectionString">
        </output>
    </trackSettings>

    <trackSettings input="LPCM-multi">
        <output outputSettingsName="{p.LpcmMultichannel.ProfileName()}"
                defaultSelection="$app_DefaultSelectionString">
        </output>
    </trackSettings>
</profile>

""";
    }
}

/// <summary>The shared settings catalog (shared/catalog/settings-catalog.json).</summary>
public sealed class SettingsCatalog
{
    public sealed class Choice { public string Value { get; set; } = ""; public string Label { get; set; } = ""; }

    public sealed class Setting
    {
        public string Key { get; set; } = "";
        public string Label { get; set; } = "";
        public string Type { get; set; } = "string";
        public string? Default { get; set; }
        public string? Help { get; set; }
        public int? Min { get; set; }
        public int? Max { get; set; }
        public List<Choice>? Choices { get; set; }
        public bool? Advanced { get; set; }
        public List<string>? Platforms { get; set; }
        public bool IsAdvanced => Advanced ?? false;
        public bool AppliesTo(string platform) => Platforms == null || Platforms.Contains(platform);
    }

    public sealed class Section
    {
        public string Id { get; set; } = "";
        public string Title { get; set; } = "";
        public List<Setting> Settings { get; set; } = new();
    }

    public sealed class Token { public string Token_ { get; set; } = ""; public string Help { get; set; } = ""; }
    public sealed class SelectionPreset { public string Name { get; set; } = ""; public string Rule { get; set; } = ""; }

    public int Version { get; set; }
    public List<Section> Sections { get; set; } = new();
    public List<Dictionary<string, string>> SelectionTokens { get; set; } = new();
    public List<SelectionPreset> SelectionPresets { get; set; } = new();

    public IEnumerable<Setting> AllSettings => Sections.SelectMany(s => s.Settings);

    public static SettingsCatalog Load(string? path = null)
    {
        path ??= Path.Combine(AppContext.BaseDirectory, "settings-catalog.json");
        try
        {
            var opts = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            return JsonSerializer.Deserialize<SettingsCatalog>(File.ReadAllText(path), opts) ?? new SettingsCatalog();
        }
        catch (Exception)
        {
            return new SettingsCatalog();
        }
    }
}
