// Generated by tools/gen-messages.py from shared/messages/codes.json. Don't edit.

namespace Bromelia.Domain;

/// <summary>Every message and error code the engine emits (plan §16). The wire form is the code text
/// (<c>rip.readErrors</c>); <see cref="Wire"/> and <see cref="Parse"/> convert.</summary>
public readonly record struct MessageCode
{
    private readonly int _index;

    private MessageCode(int index) { _index = index; }

    public static readonly MessageCode JobStarted = new(0);
    public static readonly MessageCode JobSource = new(1);
    public static readonly MessageCode JobFinished = new(2);
    public static readonly MessageCode JobCancelledByUser = new(3);
    public static readonly MessageCode JobCancelled = new(4);
    public static readonly MessageCode JobNotFound = new(5);
    public static readonly MessageCode JobNotRetryable = new(6);
    public static readonly MessageCode JobNotAwaitingDecision = new(7);
    public static readonly MessageCode JobNotQueued = new(8);
    public static readonly MessageCode JobNotInterrupted = new(9);
    public static readonly MessageCode JobUnknownStep = new(10);
    public static readonly MessageCode JobOpStarting = new(11);
    public static readonly MessageCode JobOpCancelling = new(12);
    public static readonly MessageCode JobOpAutomatic = new(13);
    public static readonly MessageCode OutcomeSucceeded = new(14);
    public static readonly MessageCode OutcomeSucceededWithReadErrors = new(15);
    public static readonly MessageCode OutcomeSucceededStepsFailed = new(16);
    public static readonly MessageCode OutcomeFailed = new(17);
    public static readonly MessageCode OutcomeCancelled = new(18);
    public static readonly MessageCode OutcomeSkipped = new(19);
    public static readonly MessageCode OutcomeInterrupted = new(20);
    public static readonly MessageCode JobStateQueued = new(21);
    public static readonly MessageCode JobStateWaitingForResources = new(22);
    public static readonly MessageCode JobStateRunning = new(23);
    public static readonly MessageCode JobStateBlocked = new(24);
    public static readonly MessageCode JobStateAwaitingDecision = new(25);
    public static readonly MessageCode JobStateFinished = new(26);
    public static readonly MessageCode ModeMkv = new(27);
    public static readonly MessageCode ModeShortMkv = new(28);
    public static readonly MessageCode ModeBackup = new(29);
    public static readonly MessageCode ModeShortBackup = new(30);
    public static readonly MessageCode ModeBackupDecrypted = new(31);
    public static readonly MessageCode ModeShortBackupDecrypted = new(32);
    public static readonly MessageCode ModeBackupThenMkv = new(33);
    public static readonly MessageCode ModeShortBackupThenMkv = new(34);
    public static readonly MessageCode ModeInfoOnly = new(35);
    public static readonly MessageCode ModeShortInfoOnly = new(36);
    public static readonly MessageCode ModeAudioCD = new(37);
    public static readonly MessageCode ModeShortAudioCD = new(38);
    public static readonly MessageCode ModeDataImage = new(39);
    public static readonly MessageCode ModeShortDataImage = new(40);
    public static readonly MessageCode DriveStateEmpty = new(41);
    public static readonly MessageCode DriveStateTrayOpen = new(42);
    public static readonly MessageCode DriveStatePresent = new(43);
    public static readonly MessageCode DriveStateLoading = new(44);
    public static readonly MessageCode DriveStateUnavailable = new(45);
    public static readonly MessageCode DriveStateUnmounting = new(46);
    public static readonly MessageCode ProcessCommand = new(47);
    public static readonly MessageCode ProcessOutput = new(48);
    public static readonly MessageCode ProcessCouldNotStart = new(49);
    public static readonly MessageCode ProcessStalled = new(50);
    public static readonly MessageCode ProcessAbandoned = new(51);
    public static readonly MessageCode ProcessFailed = new(52);
    public static readonly MessageCode ProcessSavedNothing = new(53);
    public static readonly MessageCode ProcessExitStatus = new(54);
    public static readonly MessageCode ProcessTimedOut = new(55);
    public static readonly MessageCode ProcessExited = new(56);
    public static readonly MessageCode MakemkvMessage = new(57);
    public static readonly MessageCode MakemkvNotFound = new(58);
    public static readonly MessageCode MakemkvKeyExpired = new(59);
    public static readonly MessageCode MakemkvEvaluationNotStarted = new(60);
    public static readonly MessageCode MakemkvTooOld = new(61);
    public static readonly MessageCode MakemkvLibreDrive = new(62);
    public static readonly MessageCode MakemkvLibreDriveRequired = new(63);
    public static readonly MessageCode MakemkvStalled = new(64);
    public static readonly MessageCode MakemkvSettingsFile = new(65);
    public static readonly MessageCode MakemkvProfileFile = new(66);
    public static readonly MessageCode MakemkvRegistryValues = new(67);
    public static readonly MessageCode MakemkvGuiRunning = new(68);
    public static readonly MessageCode MakemkvBetaKeyUpdated = new(69);
    public static readonly MessageCode MakemkvBetaKeyFetchFailed = new(70);
    public static readonly MessageCode MakemkvBetaKeyHttp = new(71);
    public static readonly MessageCode MakemkvBetaKeyNotFound = new(72);
    public static readonly MessageCode MakemkvBetaKeyPurchasedKept = new(73);
    public static readonly MessageCode MakemkvRegisterOk = new(74);
    public static readonly MessageCode MakemkvRegisterFailed = new(75);
    public static readonly MessageCode MakemkvDriveScanFailed = new(76);
    public static readonly MessageCode MakemkvNoSummary = new(77);
    public static readonly MessageCode MakemkvSavedMismatch = new(78);
    public static readonly MessageCode MakemkvRegistryFailed = new(79);
    public static readonly MessageCode MakemkvRegistryNotRestored = new(80);
    public static readonly MessageCode MakemkvTitleProgress = new(81);
    public static readonly MessageCode DiscOpReading = new(82);
    public static readonly MessageCode DiscReadingAgain = new(83);
    public static readonly MessageCode DiscUsingOpenedListing = new(84);
    public static readonly MessageCode DiscContinuingWithoutListing = new(85);
    public static readonly MessageCode DiscChanged = new(86);
    public static readonly MessageCode DiscChangedVolume = new(87);
    public static readonly MessageCode DiscChangedTitles = new(88);
    public static readonly MessageCode DiscChangedGeneration = new(89);
    public static readonly MessageCode DiscTitleNotInListing = new(90);
    public static readonly MessageCode DiscTitleGone = new(91);
    public static readonly MessageCode DiscTracksChanged = new(92);
    public static readonly MessageCode DiscNoTitles = new(93);
    public static readonly MessageCode DiscFound = new(94);
    public static readonly MessageCode DiscTitleNumbersChanged = new(95);
    public static readonly MessageCode DiscNoInformation = new(96);
    public static readonly MessageCode DiscNotVideo = new(97);
    public static readonly MessageCode DiscWaitingForMount = new(98);
    public static readonly MessageCode DiscMounted = new(99);
    public static readonly MessageCode DiscNotMounted = new(100);
    public static readonly MessageCode DiscLookingForArchives = new(101);
    public static readonly MessageCode DiscArchivedBefore = new(102);
    public static readonly MessageCode DiscAlreadyArchived = new(103);
    public static readonly MessageCode DiscAlreadyArchivedAsk = new(104);
    public static readonly MessageCode TitlesNoneChosenExist = new(105);
    public static readonly MessageCode TitlesManualRequired = new(106);
    public static readonly MessageCode TitlesNoneMatched = new(107);
    public static readonly MessageCode TitlesSelected = new(108);
    public static readonly MessageCode TitlesSkipped = new(109);
    public static readonly MessageCode TitlesInvalidInclude = new(110);
    public static readonly MessageCode TitlesInvalidExclude = new(111);
    public static readonly MessageCode TitlesReasonSelected = new(112);
    public static readonly MessageCode TitlesReasonExcluded = new(113);
    public static readonly MessageCode TitlesReasonShorterThan = new(114);
    public static readonly MessageCode TitlesReasonLongerThan = new(115);
    public static readonly MessageCode TitlesReasonFewerChapters = new(116);
    public static readonly MessageCode TitlesReasonMoreChapters = new(117);
    public static readonly MessageCode TitlesReasonSmallerThan = new(118);
    public static readonly MessageCode TitlesReasonLargerThan = new(119);
    public static readonly MessageCode TitlesReasonNoIncludeMatch = new(120);
    public static readonly MessageCode TitlesReasonExcludeMatch = new(121);
    public static readonly MessageCode TitlesReasonAlternateAngle = new(122);
    public static readonly MessageCode TitlesReasonDuplicateOf = new(123);
    public static readonly MessageCode TitlesReasonNotLongest = new(124);
    public static readonly MessageCode TitlesReasonNotInPattern = new(125);
    public static readonly MessageCode TitlesReasonInvalidPattern = new(126);
    public static readonly MessageCode TitlesReasonChooseManually = new(127);
    public static readonly MessageCode TitlesReasonOverLimit = new(128);
    public static readonly MessageCode RipNeedsMkvmergeForTracks = new(129);
    public static readonly MessageCode RipRipping = new(130);
    public static readonly MessageCode RipRippingTitle = new(131);
    public static readonly MessageCode RipTitleFailed = new(132);
    public static readonly MessageCode RipFailed = new(133);
    public static readonly MessageCode RipTitlesFailed = new(134);
    public static readonly MessageCode RipTitleReason = new(135);
    public static readonly MessageCode RipKeptUnderMakemkvName = new(136);
    public static readonly MessageCode RipCheckFailed = new(137);
    public static readonly MessageCode RipReadErrors = new(138);
    public static readonly MessageCode RipOnePass = new(139);
    public static readonly MessageCode RipOnePassMismatch = new(140);
    public static readonly MessageCode RipOnePassListing = new(141);
    public static readonly MessageCode RipRenamed = new(142);
    public static readonly MessageCode RipRenameFailed = new(143);
    public static readonly MessageCode RipDiscInfoWritten = new(144);
    public static readonly MessageCode RipcheckCannotCheck = new(145);
    public static readonly MessageCode RipcheckChecking = new(146);
    public static readonly MessageCode RipcheckUnreadable = new(147);
    public static readonly MessageCode RipcheckMismatch = new(148);
    public static readonly MessageCode RipcheckNoTracks = new(149);
    public static readonly MessageCode RipcheckNoVideo = new(150);
    public static readonly MessageCode RipcheckDuration = new(151);
    public static readonly MessageCode RipcheckNoDuration = new(152);
    public static readonly MessageCode RipcheckMoreTracks = new(153);
    public static readonly MessageCode RipcheckChapters = new(154);
    public static readonly MessageCode RipcheckNote = new(155);
    public static readonly MessageCode RipcheckChecked = new(156);
    public static readonly MessageCode RipcheckTrackSubset = new(157);
    public static readonly MessageCode RemuxRemoving = new(158);
    public static readonly MessageCode RemuxUnreadable = new(159);
    public static readonly MessageCode RemuxLayoutDiffers = new(160);
    public static readonly MessageCode RemuxKept = new(161);
    public static readonly MessageCode RemuxReplaceFailed = new(162);
    public static readonly MessageCode RemuxFailed = new(163);
    public static readonly MessageCode BackupNeedsDrive = new(164);
    public static readonly MessageCode BackupBackingUp = new(165);
    public static readonly MessageCode BackupFailed = new(166);
    public static readonly MessageCode BackupCheckFailed = new(167);
    public static readonly MessageCode BackupSaved = new(168);
    public static readonly MessageCode BackupFolderInsteadOfIso = new(169);
    public static readonly MessageCode BackupRenamed = new(170);
    public static readonly MessageCode BackupRemoved = new(171);
    public static readonly MessageCode StructureNotCreated = new(172);
    public static readonly MessageCode StructureIsFolder = new(173);
    public static readonly MessageCode StructureUnreadable = new(174);
    public static readonly MessageCode StructureNotImage = new(175);
    public static readonly MessageCode StructureNotFolder = new(176);
    public static readonly MessageCode StructureBdmvIndexMissing = new(177);
    public static readonly MessageCode StructureVideoTsIfoMissing = new(178);
    public static readonly MessageCode StructureNoDiscFolder = new(179);
    public static readonly MessageCode SpaceReport = new(180);
    public static readonly MessageCode SpaceInsufficient = new(181);
    public static readonly MessageCode SpaceMakemkvWarning = new(182);
    public static readonly MessageCode DriveRenumbered = new(183);
    public static readonly MessageCode DriveEjecting = new(184);
    public static readonly MessageCode DriveEjected = new(185);
    public static readonly MessageCode DriveEjectFailed = new(186);
    public static readonly MessageCode DriveCloseTrayFailed = new(187);
    public static readonly MessageCode DriveCloseTraysFailed = new(188);
    public static readonly MessageCode DriveNotFound = new(189);
    public static readonly MessageCode DriveNoDisc = new(190);
    public static readonly MessageCode DriveBusy = new(191);
    public static readonly MessageCode DriveSizeUnknown = new(192);
    public static readonly MessageCode DrivePartialSector = new(193);
    public static readonly MessageCode EpisodesReadingMenus = new(194);
    public static readonly MessageCode EpisodesCannotOpenVideoTs = new(195);
    public static readonly MessageCode EpisodesPlan = new(196);
    public static readonly MessageCode EpisodesChapterMismatch = new(197);
    public static readonly MessageCode EpisodesNotEpisodes = new(198);
    public static readonly MessageCode EpisodesReadingNumbers = new(199);
    public static readonly MessageCode EpisodesRange = new(200);
    public static readonly MessageCode EpisodesHowTyped = new(201);
    public static readonly MessageCode EpisodesHowMenu = new(202);
    public static readonly MessageCode EpisodesHowMenuUnclear = new(203);
    public static readonly MessageCode EpisodesHowOcrUnavailable = new(204);
    public static readonly MessageCode EpisodesHowPreviousDisc = new(205);
    public static readonly MessageCode EpisodesHowFromOne = new(206);
    public static readonly MessageCode EpisodesHowNoNumber = new(207);
    public static readonly MessageCode EpisodesPreviousDiscGap = new(208);
    public static readonly MessageCode EpisodesLookingForPrevious = new(209);
    public static readonly MessageCode EpisodesSplitNeedsMkvmerge = new(210);
    public static readonly MessageCode EpisodesSplitting = new(211);
    public static readonly MessageCode EpisodesDurationMismatch = new(212);
    public static readonly MessageCode EpisodesChaptersMisaligned = new(213);
    public static readonly MessageCode EpisodesSplitFailed = new(214);
    public static readonly MessageCode EpisodesSplit = new(215);
    public static readonly MessageCode EpisodesRemovedPlayAll = new(216);
    public static readonly MessageCode IdentityResolved = new(217);
    public static readonly MessageCode IdentityReasonChosen = new(218);
    public static readonly MessageCode IdentityReasonLabelMarkers = new(219);
    public static readonly MessageCode IdentityReasonMenuEpisodes = new(220);
    public static readonly MessageCode IdentityReasonEpisodeTitles = new(221);
    public static readonly MessageCode IdentityReasonNone = new(222);
    public static readonly MessageCode IdentityReasonProvider = new(223);
    public static readonly MessageCode IdentityModeByFormat = new(224);
    public static readonly MessageCode MetadataLookingUp = new(225);
    public static readonly MessageCode MetadataLookingUpId = new(226);
    public static readonly MessageCode MetadataMatch = new(227);
    public static readonly MessageCode MetadataHowChosen = new(228);
    public static readonly MessageCode MetadataHowOnly = new(229);
    public static readonly MessageCode MetadataHowBest = new(230);
    public static readonly MessageCode MetadataNotFound = new(231);
    public static readonly MessageCode MetadataIdNotFound = new(232);
    public static readonly MessageCode MetadataNotAnId = new(233);
    public static readonly MessageCode MetadataFailed = new(234);
    public static readonly MessageCode MetadataHttp = new(235);
    public static readonly MessageCode MetadataIdUnsupported = new(236);
    public static readonly MessageCode MetadataEmptyAnswer = new(237);
    public static readonly MessageCode MetadataEpisodeTitlesLooking = new(238);
    public static readonly MessageCode MetadataNoEpisodes = new(239);
    public static readonly MessageCode MetadataSeasonMissing = new(240);
    public static readonly MessageCode MetadataEpisodeTitles = new(241);
    public static readonly MessageCode MetadataAbsoluteOrder = new(242);
    public static readonly MessageCode MetadataNoAbsoluteOrder = new(243);
    public static readonly MessageCode MetadataEpisodeTitlesFailed = new(244);
    public static readonly MessageCode HttpStatus = new(245);
    public static readonly MessageCode HttpFailed = new(246);
    public static readonly MessageCode PublishWriting = new(247);
    public static readonly MessageCode PublishWritten = new(248);
    public static readonly MessageCode PublishWriteFailed = new(249);
    public static readonly MessageCode PublishPosterFailed = new(250);
    public static readonly MessageCode ArchiveOutputFolder = new(251);
    public static readonly MessageCode ArchiveHashing = new(252);
    public static readonly MessageCode ArchiveHashFailed = new(253);
    public static readonly MessageCode ArchiveMoving = new(254);
    public static readonly MessageCode ArchiveMoved = new(255);
    public static readonly MessageCode ArchiveKeptApart = new(256);
    public static readonly MessageCode ArchiveMoveFailed = new(257);
    public static readonly MessageCode ArchiveSomeNotMoved = new(258);
    public static readonly MessageCode ArchiveChecksumsWritten = new(259);
    public static readonly MessageCode ArchiveWriteFailed = new(260);
    public static readonly MessageCode FsNotFound = new(261);
    public static readonly MessageCode FsAlreadyExists = new(262);
    public static readonly MessageCode FsParentMissing = new(263);
    public static readonly MessageCode FsFailed = new(264);
    public static readonly MessageCode StoreFailed = new(265);
    public static readonly MessageCode KeystoreFailed = new(266);
    public static readonly MessageCode ArchiveRecordWritten = new(267);
    public static readonly MessageCode ArchiveRenameFailed = new(268);
    public static readonly MessageCode ArchiveSynced = new(269);
    public static readonly MessageCode ArchiveNoteTitle = new(270);
    public static readonly MessageCode ArchiveNoteNotFinished = new(271);
    public static readonly MessageCode ArchiveNoteReadErrors = new(272);
    public static readonly MessageCode ArchiveNoteLogs = new(273);
    public static readonly MessageCode ArchiveNoteFullLog = new(274);
    public static readonly MessageCode CommitRolledForward = new(275);
    public static readonly MessageCode CommitMerged = new(276);
    public static readonly MessageCode CommitQuarantined = new(277);
    public static readonly MessageCode LibraryOffline = new(278);
    public static readonly MessageCode LibraryNone = new(279);
    public static readonly MessageCode LibraryBack = new(280);
    public static readonly MessageCode LibraryMarkerMismatch = new(281);
    public static readonly MessageCode LibraryFolderExists = new(282);
    public static readonly MessageCode LibraryNotFound = new(283);
    public static readonly MessageCode LibraryPathMissing = new(284);
    public static readonly MessageCode LibraryAlreadyAttached = new(285);
    public static readonly MessageCode LibraryNotAttached = new(286);
    public static readonly MessageCode UnitNotFound = new(287);
    public static readonly MessageCode CheckOk = new(288);
    public static readonly MessageCode CheckDamaged = new(289);
    public static readonly MessageCode CheckPartChanged = new(290);
    public static readonly MessageCode CheckPartUnreadable = new(291);
    public static readonly MessageCode CheckPartMissing = new(292);
    public static readonly MessageCode CheckSumsUnreadable = new(293);
    public static readonly MessageCode CheckSumsEmpty = new(294);
    public static readonly MessageCode CheckAlreadyRunning = new(295);
    public static readonly MessageCode CheckVerifying = new(296);
    public static readonly MessageCode CheckDamagedFound = new(297);
    public static readonly MessageCode CheckNotifyAllOk = new(298);
    public static readonly MessageCode CheckNotifyDamaged = new(299);
    public static readonly MessageCode CheckNotifyEveryFileMatches = new(300);
    public static readonly MessageCode CheckNotifyMore = new(301);
    public static readonly MessageCode CheckNotifyFolder = new(302);
    public static readonly MessageCode PostRunning = new(303);
    public static readonly MessageCode PostHandbrakeMissing = new(304);
    public static readonly MessageCode PostNoMkv = new(305);
    public static readonly MessageCode PostCannotCreateFolder = new(306);
    public static readonly MessageCode PostStarted = new(307);
    public static readonly MessageCode PostOutput = new(308);
    public static readonly MessageCode PostCouldNotStart = new(309);
    public static readonly MessageCode PostFailed = new(310);
    public static readonly MessageCode PostQueued = new(311);
    public static readonly MessageCode PostTest = new(312);
    public static readonly MessageCode StepNotFound = new(313);
    public static readonly MessageCode NotifyBadUrl = new(314);
    public static readonly MessageCode NotifyHttpFailed = new(315);
    public static readonly MessageCode NotifyFailed = new(316);
    public static readonly MessageCode NotifyNeedsApprise = new(317);
    public static readonly MessageCode NotifyAppriseFailed = new(318);
    public static readonly MessageCode NotifyTitleJob = new(319);
    public static readonly MessageCode NotifyBodySaved = new(320);
    public static readonly MessageCode NotifyBodyReadErrors = new(321);
    public static readonly MessageCode NotifyBodyError = new(322);
    public static readonly MessageCode NotifyTestTitle = new(323);
    public static readonly MessageCode NotifyTestBody = new(324);
    public static readonly MessageCode NotifyNotFound = new(325);
    public static readonly MessageCode OtherNeedsDrive = new(326);
    public static readonly MessageCode OtherAudioNeedsRipper = new(327);
    public static readonly MessageCode OtherRippingAudio = new(328);
    public static readonly MessageCode OtherCopyingData = new(329);
    public static readonly MessageCode OtherImageCheckFailed = new(330);
    public static readonly MessageCode OtherReadError = new(331);
    public static readonly MessageCode OtherEmptyDisc = new(332);
    public static readonly MessageCode SessionOpening = new(333);
    public static readonly MessageCode SessionNoTitlesHere = new(334);
    public static readonly MessageCode SessionNoTitles = new(335);
    public static readonly MessageCode SessionOpeningContainer = new(336);
    public static readonly MessageCode SessionNotOpen = new(337);
    public static readonly MessageCode SessionNoTitlesChosen = new(338);
    public static readonly MessageCode SessionNothingToRip = new(339);
    public static readonly MessageCode SessionNotFound = new(340);
    public static readonly MessageCode SessionStale = new(341);
    public static readonly MessageCode SessionCancelled = new(342);
    public static readonly MessageCode DecisionArchivedBefore = new(343);
    public static readonly MessageCode DecisionContinueInterrupted = new(344);
    public static readonly MessageCode DecisionAmbiguousLookup = new(345);
    public static readonly MessageCode DecisionAnswerRipAgain = new(346);
    public static readonly MessageCode DecisionAnswerSkip = new(347);
    public static readonly MessageCode DecisionAnswerEject = new(348);
    public static readonly MessageCode DecisionAnswerContinue = new(349);
    public static readonly MessageCode DecisionAnswerStartOver = new(350);
    public static readonly MessageCode DecisionAnswerKeepApart = new(351);
    public static readonly MessageCode RecoveryInterrupted = new(352);
    public static readonly MessageCode RecoveryRequeued = new(353);
    public static readonly MessageCode RecoveryResumed = new(354);
    public static readonly MessageCode RecoveryResumedFromBackup = new(355);
    public static readonly MessageCode RecoveryKeptApart = new(356);
    public static readonly MessageCode RecoverySummary = new(357);
    public static readonly MessageCode ConfigInvalid = new(358);
    public static readonly MessageCode ConfigUnknownKey = new(359);
    public static readonly MessageCode ConfigRequired = new(360);
    public static readonly MessageCode ConfigInvalidValue = new(361);
    public static readonly MessageCode ConfigInvalidRegex = new(362);
    public static readonly MessageCode ConfigInvalidIndexPattern = new(363);
    public static readonly MessageCode ConfigUnknownReference = new(364);
    public static readonly MessageCode ConfigDuplicateId = new(365);
    public static readonly MessageCode ConfigSecretInline = new(366);
    public static readonly MessageCode ConfigSecretMissing = new(367);
    public static readonly MessageCode ConfigNetworkNeedsToken = new(368);
    public static readonly MessageCode ConfigPortInvalid = new(369);
    public static readonly MessageCode ConfigTlsNeedsBoth = new(370);
    public static readonly MessageCode ConfigNotVideoMode = new(371);
    public static readonly MessageCode ConfigVersionConflict = new(372);
    public static readonly MessageCode ConfigRejected = new(373);
    public static readonly MessageCode ConfigUnknownMode = new(374);
    public static readonly MessageCode ConfigDriveNotFound = new(375);
    public static readonly MessageCode ConfigSaveFailed = new(376);
    public static readonly MessageCode ConfigMigrated = new(377);
    public static readonly MessageCode ConfigMigrationValueDropped = new(378);
    public static readonly MessageCode ConfigBadBundle = new(379);
    public static readonly MessageCode ServerTokenRequired = new(380);
    public static readonly MessageCode ServerHostNotAllowed = new(381);
    public static readonly MessageCode ServerHeaderMissing = new(382);
    public static readonly MessageCode ServerOriginNotAllowed = new(383);
    public static readonly MessageCode ServerReadOnlyToken = new(384);
    public static readonly MessageCode ServerNotFound = new(385);
    public static readonly MessageCode ServerMethodNotAllowed = new(386);
    public static readonly MessageCode ServerBadRequest = new(387);
    public static readonly MessageCode ServerPageMissing = new(388);
    public static readonly MessageCode ServerStartFailed = new(389);
    public static readonly MessageCode ServerListening = new(390);
    public static readonly MessageCode ServerStopping = new(391);
    public static readonly MessageCode TlsCannotRead = new(392);
    public static readonly MessageCode TlsOpensslFailed = new(393);
    public static readonly MessageCode TlsImportFailed = new(394);
    public static readonly MessageCode TlsKeychainFailed = new(395);
    public static readonly MessageCode TlsUnusable = new(396);
    public static readonly MessageCode HostAlreadyRunning = new(397);
    public static readonly MessageCode HostUnknownOption = new(398);
    public static readonly MessageCode HostOptionNeedsValue = new(399);
    public static readonly MessageCode HostStarted = new(400);
    public static readonly MessageCode HostLibrary = new(401);
    public static readonly MessageCode HostStopping = new(402);
    public static readonly MessageCode HostServiceInstalled = new(403);
    public static readonly MessageCode HostServiceRemoved = new(404);
    public static readonly MessageCode HostServiceFailed = new(405);
    public static readonly MessageCode HostCannotFindProgram = new(406);
    public static readonly MessageCode HostStopRequested = new(407);
    public static readonly MessageCode PowerUnavailable = new(408);
    public static readonly MessageCode ToolMissing = new(409);
    public static readonly MessageCode ToolNotFoundAt = new(410);
    public static readonly MessageCode ToolVersion = new(411);
    public static readonly MessageCode ReplicaLagging = new(412);
    public static readonly MessageCode ReplicaVerifyFailed = new(413);
    public static readonly MessageCode RepairRepaired = new(414);
    public static readonly MessageCode RepairImpossible = new(415);
    public static readonly MessageCode InternalUnexpected = new(416);

    private static readonly string[] Codes =
    {
        "job.started",
        "job.source",
        "job.finished",
        "job.cancelledByUser",
        "job.cancelled",
        "job.notFound",
        "job.notRetryable",
        "job.notAwaitingDecision",
        "job.notQueued",
        "job.notInterrupted",
        "job.unknownStep",
        "job.op.starting",
        "job.op.cancelling",
        "job.op.automatic",
        "outcome.succeeded",
        "outcome.succeededWithReadErrors",
        "outcome.succeededStepsFailed",
        "outcome.failed",
        "outcome.cancelled",
        "outcome.skipped",
        "outcome.interrupted",
        "jobState.queued",
        "jobState.waitingForResources",
        "jobState.running",
        "jobState.blocked",
        "jobState.awaitingDecision",
        "jobState.finished",
        "mode.mkv",
        "modeShort.mkv",
        "mode.backup",
        "modeShort.backup",
        "mode.backupDecrypted",
        "modeShort.backupDecrypted",
        "mode.backupThenMkv",
        "modeShort.backupThenMkv",
        "mode.infoOnly",
        "modeShort.infoOnly",
        "mode.audioCD",
        "modeShort.audioCD",
        "mode.dataImage",
        "modeShort.dataImage",
        "driveState.empty",
        "driveState.trayOpen",
        "driveState.present",
        "driveState.loading",
        "driveState.unavailable",
        "driveState.unmounting",
        "process.command",
        "process.output",
        "process.couldNotStart",
        "process.stalled",
        "process.abandoned",
        "process.failed",
        "process.savedNothing",
        "process.exitStatus",
        "process.timedOut",
        "process.exited",
        "makemkv.message",
        "makemkv.notFound",
        "makemkv.keyExpired",
        "makemkv.evaluationNotStarted",
        "makemkv.tooOld",
        "makemkv.libreDrive",
        "makemkv.libreDriveRequired",
        "makemkv.stalled",
        "makemkv.settingsFile",
        "makemkv.profileFile",
        "makemkv.registryValues",
        "makemkv.guiRunning",
        "makemkv.betaKey.updated",
        "makemkv.betaKey.fetchFailed",
        "makemkv.betaKey.http",
        "makemkv.betaKey.notFound",
        "makemkv.betaKey.purchasedKept",
        "makemkv.register.ok",
        "makemkv.register.failed",
        "makemkv.driveScanFailed",
        "makemkv.noSummary",
        "makemkv.savedMismatch",
        "makemkv.registryFailed",
        "makemkv.registryNotRestored",
        "makemkv.titleProgress",
        "disc.op.reading",
        "disc.readingAgain",
        "disc.usingOpenedListing",
        "disc.continuingWithoutListing",
        "disc.changed",
        "disc.changed.volume",
        "disc.changed.titles",
        "disc.changed.generation",
        "disc.titleNotInListing",
        "disc.titleGone",
        "disc.tracksChanged",
        "disc.noTitles",
        "disc.found",
        "disc.titleNumbersChanged",
        "disc.noInformation",
        "disc.notVideo",
        "disc.waitingForMount",
        "disc.mounted",
        "disc.notMounted",
        "disc.lookingForArchives",
        "disc.archivedBefore",
        "disc.alreadyArchived",
        "disc.alreadyArchivedAsk",
        "titles.noneChosenExist",
        "titles.manualRequired",
        "titles.noneMatched",
        "titles.selected",
        "titles.skipped",
        "titles.invalidInclude",
        "titles.invalidExclude",
        "titles.reason.selected",
        "titles.reason.excluded",
        "titles.reason.shorterThan",
        "titles.reason.longerThan",
        "titles.reason.fewerChapters",
        "titles.reason.moreChapters",
        "titles.reason.smallerThan",
        "titles.reason.largerThan",
        "titles.reason.noIncludeMatch",
        "titles.reason.excludeMatch",
        "titles.reason.alternateAngle",
        "titles.reason.duplicateOf",
        "titles.reason.notLongest",
        "titles.reason.notInPattern",
        "titles.reason.invalidPattern",
        "titles.reason.chooseManually",
        "titles.reason.overLimit",
        "rip.needsMkvmergeForTracks",
        "rip.ripping",
        "rip.rippingTitle",
        "rip.titleFailed",
        "rip.failed",
        "rip.titlesFailed",
        "rip.titleReason",
        "rip.keptUnderMakemkvName",
        "rip.checkFailed",
        "rip.readErrors",
        "rip.onePass",
        "rip.onePassMismatch",
        "rip.onePassListing",
        "rip.renamed",
        "rip.renameFailed",
        "rip.discInfoWritten",
        "ripcheck.cannotCheck",
        "ripcheck.checking",
        "ripcheck.unreadable",
        "ripcheck.mismatch",
        "ripcheck.noTracks",
        "ripcheck.noVideo",
        "ripcheck.duration",
        "ripcheck.noDuration",
        "ripcheck.moreTracks",
        "ripcheck.chapters",
        "ripcheck.note",
        "ripcheck.checked",
        "ripcheck.trackSubset",
        "remux.removing",
        "remux.unreadable",
        "remux.layoutDiffers",
        "remux.kept",
        "remux.replaceFailed",
        "remux.failed",
        "backup.needsDrive",
        "backup.backingUp",
        "backup.failed",
        "backup.checkFailed",
        "backup.saved",
        "backup.folderInsteadOfIso",
        "backup.renamed",
        "backup.removed",
        "structure.notCreated",
        "structure.isFolder",
        "structure.unreadable",
        "structure.notImage",
        "structure.notFolder",
        "structure.bdmvIndexMissing",
        "structure.videoTsIfoMissing",
        "structure.noDiscFolder",
        "space.report",
        "space.insufficient",
        "space.makemkvWarning",
        "drive.renumbered",
        "drive.ejecting",
        "drive.ejected",
        "drive.ejectFailed",
        "drive.closeTrayFailed",
        "drive.closeTraysFailed",
        "drive.notFound",
        "drive.noDisc",
        "drive.busy",
        "drive.sizeUnknown",
        "drive.partialSector",
        "episodes.readingMenus",
        "episodes.cannotOpenVideoTs",
        "episodes.plan",
        "episodes.chapterMismatch",
        "episodes.notEpisodes",
        "episodes.readingNumbers",
        "episodes.range",
        "episodes.how.typed",
        "episodes.how.menu",
        "episodes.how.menuUnclear",
        "episodes.how.ocrUnavailable",
        "episodes.how.previousDisc",
        "episodes.how.fromOne",
        "episodes.how.noNumber",
        "episodes.previousDiscGap",
        "episodes.lookingForPrevious",
        "episodes.splitNeedsMkvmerge",
        "episodes.splitting",
        "episodes.durationMismatch",
        "episodes.chaptersMisaligned",
        "episodes.splitFailed",
        "episodes.split",
        "episodes.removedPlayAll",
        "identity.resolved",
        "identity.reason.chosen",
        "identity.reason.labelMarkers",
        "identity.reason.menuEpisodes",
        "identity.reason.episodeTitles",
        "identity.reason.none",
        "identity.reason.provider",
        "identity.modeByFormat",
        "metadata.lookingUp",
        "metadata.lookingUpId",
        "metadata.match",
        "metadata.how.chosen",
        "metadata.how.only",
        "metadata.how.best",
        "metadata.notFound",
        "metadata.idNotFound",
        "metadata.notAnId",
        "metadata.failed",
        "metadata.http",
        "metadata.idUnsupported",
        "metadata.emptyAnswer",
        "metadata.episodeTitlesLooking",
        "metadata.noEpisodes",
        "metadata.seasonMissing",
        "metadata.episodeTitles",
        "metadata.absoluteOrder",
        "metadata.noAbsoluteOrder",
        "metadata.episodeTitlesFailed",
        "http.status",
        "http.failed",
        "publish.writing",
        "publish.written",
        "publish.writeFailed",
        "publish.posterFailed",
        "archive.outputFolder",
        "archive.hashing",
        "archive.hashFailed",
        "archive.moving",
        "archive.moved",
        "archive.keptApart",
        "archive.moveFailed",
        "archive.someNotMoved",
        "archive.checksumsWritten",
        "archive.writeFailed",
        "fs.notFound",
        "fs.alreadyExists",
        "fs.parentMissing",
        "fs.failed",
        "store.failed",
        "keystore.failed",
        "archive.recordWritten",
        "archive.renameFailed",
        "archive.synced",
        "archive.note.title",
        "archive.note.notFinished",
        "archive.note.readErrors",
        "archive.note.logs",
        "archive.note.fullLog",
        "commit.rolledForward",
        "commit.merged",
        "commit.quarantined",
        "library.offline",
        "library.none",
        "library.back",
        "library.markerMismatch",
        "library.folderExists",
        "library.notFound",
        "library.pathMissing",
        "library.alreadyAttached",
        "library.notAttached",
        "unit.notFound",
        "check.ok",
        "check.damaged",
        "check.part.changed",
        "check.part.unreadable",
        "check.part.missing",
        "check.sumsUnreadable",
        "check.sumsEmpty",
        "check.alreadyRunning",
        "check.verifying",
        "check.damagedFound",
        "check.notify.allOk",
        "check.notify.damaged",
        "check.notify.everyFileMatches",
        "check.notify.more",
        "check.notify.folder",
        "post.running",
        "post.handbrakeMissing",
        "post.noMkv",
        "post.cannotCreateFolder",
        "post.started",
        "post.output",
        "post.couldNotStart",
        "post.failed",
        "post.queued",
        "post.test",
        "step.notFound",
        "notify.badUrl",
        "notify.httpFailed",
        "notify.failed",
        "notify.needsApprise",
        "notify.appriseFailed",
        "notify.title.job",
        "notify.body.saved",
        "notify.body.readErrors",
        "notify.body.error",
        "notify.test.title",
        "notify.test.body",
        "notify.notFound",
        "other.needsDrive",
        "other.audioNeedsRipper",
        "other.rippingAudio",
        "other.copyingData",
        "other.imageCheckFailed",
        "other.readError",
        "other.emptyDisc",
        "session.opening",
        "session.noTitlesHere",
        "session.noTitles",
        "session.openingContainer",
        "session.notOpen",
        "session.noTitlesChosen",
        "session.nothingToRip",
        "session.notFound",
        "session.stale",
        "session.cancelled",
        "decision.archivedBefore",
        "decision.continueInterrupted",
        "decision.ambiguousLookup",
        "decision.answer.ripAgain",
        "decision.answer.skip",
        "decision.answer.eject",
        "decision.answer.continue",
        "decision.answer.startOver",
        "decision.answer.keepApart",
        "recovery.interrupted",
        "recovery.requeued",
        "recovery.resumed",
        "recovery.resumedFromBackup",
        "recovery.keptApart",
        "recovery.summary",
        "config.invalid",
        "config.unknownKey",
        "config.required",
        "config.invalidValue",
        "config.invalidRegex",
        "config.invalidIndexPattern",
        "config.unknownReference",
        "config.duplicateId",
        "config.secretInline",
        "config.secretMissing",
        "config.networkNeedsToken",
        "config.portInvalid",
        "config.tlsNeedsBoth",
        "config.notVideoMode",
        "config.versionConflict",
        "config.rejected",
        "config.unknownMode",
        "config.driveNotFound",
        "config.saveFailed",
        "config.migrated",
        "config.migration.valueDropped",
        "config.badBundle",
        "server.tokenRequired",
        "server.hostNotAllowed",
        "server.headerMissing",
        "server.originNotAllowed",
        "server.readOnlyToken",
        "server.notFound",
        "server.methodNotAllowed",
        "server.badRequest",
        "server.pageMissing",
        "server.startFailed",
        "server.listening",
        "server.stopping",
        "tls.cannotRead",
        "tls.opensslFailed",
        "tls.importFailed",
        "tls.keychainFailed",
        "tls.unusable",
        "host.alreadyRunning",
        "host.unknownOption",
        "host.optionNeedsValue",
        "host.started",
        "host.library",
        "host.stopping",
        "host.serviceInstalled",
        "host.serviceRemoved",
        "host.serviceFailed",
        "host.cannotFindProgram",
        "host.stopRequested",
        "power.unavailable",
        "tool.missing",
        "tool.notFoundAt",
        "tool.version",
        "replica.lagging",
        "replica.verifyFailed",
        "repair.repaired",
        "repair.impossible",
        "internal.unexpected",
    };

    private static readonly System.Collections.Generic.Dictionary<string, int> Index = BuildIndex();

    private static System.Collections.Generic.Dictionary<string, int> BuildIndex()
    {
        var d = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal);
        for (int i = 0; i < Codes.Length; i++) d[Codes[i]] = i;
        return d;
    }

    /// <summary>Every code, in the order of codes.json.</summary>
    public static System.Collections.Generic.IEnumerable<MessageCode> All()
    {
        for (int i = 0; i < Codes.Length; i++) yield return new MessageCode(i);
    }

    /// <summary>The wire form: <c>rip.readErrors</c>.</summary>
    public static string Wire(MessageCode code) => Codes[code._index];

    /// <summary>The code for a wire form; null when it isn't one.</summary>
    public static MessageCode? Parse(string text) => Index.TryGetValue(text, out var i) ? new MessageCode(i) : null;

    public override string ToString() => Codes[_index];
}
