/* bro-profile-xml.c */
#include "bro-profile-xml.h"

#include "bro-config-private.h"
#include "bro-issue.h"

#include <string.h>

#define M bro_json_value_member

static void
escape_into (GString *s, const char *text)
{
  for (const char *p = text; *p; p++)
    switch (*p) {
    case '&': g_string_append (s, "&amp;"); break;
    case '<': g_string_append (s, "&lt;"); break;
    case '>': g_string_append (s, "&gt;"); break;
    case '"': g_string_append (s, "&quot;"); break;
    default: g_string_append_c (s, *p);
    }
}

static void
track (GString *x, const char *input, const char *output)
{
  g_string_append_printf (x, "    <trackSettings input=\"%s\">\n        <output outputSettingsName=\"", input);
  escape_into (x, output);
  g_string_append (x, "\"\n                defaultSelection=\"$app_DefaultSelectionString\">\n        </output>\n    </trackSettings>\n");
}

char *
bro_profile_xml_render (BroJsonValue *generated)
{
  g_autoptr (GPtrArray) issues = g_ptr_array_new_with_free_func ((GDestroyNotify) bro_issue_free);
  BroJsonValue *node = M (M (_bro_schema_def ("MakemkvProfile"), "properties"), "generated");
  g_autoptr (BroJsonValue) g = _bro_schema_normalize (generated, node, "", TRUE, issues);
  const char *rule = bro_json_value_get_string (M (g, "selectionRule"), "");
  g_autofree char *trimmed = g_strstrip (g_strdup (rule));
  if (!*trimmed)
    rule = BRO_PROFILE_XML_MAKEMKV_DEFAULT_SELECTION;
  GString *x = g_string_new ("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
                             "<!-- Generated by Bromelia. Edit the profile in Bromelia instead of this file. -->\n"
                             "<profile>\n"
                             "    <name lang=\"eng\">");
  escape_into (x, bro_json_value_get_string (M (g, "name"), ""));
  g_string_append (x, "</name>\n\n    <mkvSettings\n");
  static const char *const flags[] = { "ignoreForcedSubtitlesFlag", "useISO639Type2T", "setFirstAudioTrackAsDefault",
                                       "setFirstSubtitleTrackAsDefault", "setFirstForcedSubtitleTrackAsDefault",
                                       "insertFirstChapter00IfMissing" };
  for (gsize i = 0; i < G_N_ELEMENTS (flags); i++)
    g_string_append_printf (x, "        %s=\"%s\"\n", flags[i], bro_json_value_get_bool (M (g, flags[i]), FALSE) ? "true" : "false");
  g_string_append (x, "    />\n\n    <profileSettings\n        app_DefaultSelectionString=\"");
  escape_into (x, rule);
  g_string_append (x, "\"\n    />\n\n"
                      "    <outputSettings name=\"copy\" outputFormat=\"directCopy\">\n"
                      "        <description lang=\"eng\">Copy track as is</description>\n"
                      "    </outputSettings>\n\n"
                      "    <outputSettings name=\"lpcm\" outputFormat=\"LPCM-raw\">\n"
                      "        <description lang=\"eng\">Save as raw LPCM</description>\n"
                      "    </outputSettings>\n\n"
                      "    <outputSettings name=\"wavex\" outputFormat=\"LPCM-wavex\">\n"
                      "        <description lang=\"eng\">Save as LPCM in WAV container</description>\n"
                      "    </outputSettings>\n\n"
                      "    <outputSettings name=\"flac-best\" outputFormat=\"FLAC\">\n"
                      "        <description lang=\"eng\">Save as FLAC (best compression)</description>\n"
                      "        <extraArgs>-compression_level 12</extraArgs>\n"
                      "    </outputSettings>\n\n"
                      "    <outputSettings name=\"flac-fast\" outputFormat=\"FLAC\">\n"
                      "        <description lang=\"eng\">Save as FLAC (fast compression)</description>\n"
                      "        <extraArgs>-compression_level 5</extraArgs>\n"
                      "    </outputSettings>\n\n");
  track (x, "default", "copy");
  g_string_append_c (x, '\n');
  track (x, "LPCM-stereo", bro_json_value_get_string (M (g, "lpcmStereo"), ""));
  g_string_append_c (x, '\n');
  track (x, "LPCM-multi", bro_json_value_get_string (M (g, "lpcmMultichannel"), ""));
  g_string_append (x, "</profile>\n");
  return g_string_free (x, FALSE);
}
