/* bro-makemkv.c — MakeMKV files, per-drive environments, command lines, catalog and process runner. */
#include "bro-makemkv.h"
#include "bro-logic.h"

#include <errno.h>
#include <json-glib/json-glib.h>
#include <signal.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#ifdef G_OS_UNIX
#include <glib-unix.h>
#include <sys/wait.h>
#include <unistd.h>
#endif

/* ---- helpers ---- */

void
bro_ptr_array_add_all (GPtrArray *a, const char *first, ...)
{
  va_list ap;
  va_start (ap, first);
  for (const char *s = first; s; s = va_arg (ap, const char *))
    g_ptr_array_add (a, g_strdup (s));
  va_end (ap);
}

char **
bro_ptr_array_to_strv (GPtrArray *a)
{
  char **v = g_new0 (char *, a->len + 1);
  for (guint i = 0; i < a->len; i++)
    v[i] = g_strdup (a->pdata[i]);
  return v;
}

/* ---- sources ---- */

BroSource *
bro_source_new_drive (int index, const char *device)
{
  BroSource *s = g_new0 (BroSource, 1);
  s->kind = BRO_SOURCE_DRIVE;
  s->index = index;
  s->path = g_strdup (device ? device : "");
  return s;
}

BroSource *
bro_source_new_path (BroSourceKind kind, const char *path)
{
  BroSource *s = g_new0 (BroSource, 1);
  s->kind = kind;
  s->path = g_strdup (path);
  return s;
}

BroSource *
bro_source_copy (const BroSource *s)
{
  BroSource *c = g_new0 (BroSource, 1);
  c->kind = s->kind;
  c->index = s->index;
  c->path = g_strdup (s->path);
  return c;
}

void
bro_source_free (BroSource *s)
{
  if (!s)
    return;
  g_free (s->path);
  g_free (s);
}

char *
bro_source_info_argument (const BroSource *s)
{
  switch (s->kind)
    {
    case BRO_SOURCE_DRIVE:
      return *s->path ? g_strdup_printf ("dev:%s", s->path) : g_strdup_printf ("disc:%d", s->index);
    case BRO_SOURCE_ISO:
      return g_strdup_printf ("iso:%s", s->path);
    default:
      return g_strdup_printf ("file:%s", s->path);
    }
}

char *
bro_source_backup_argument (const BroSource *s)
{
  return s->kind == BRO_SOURCE_DRIVE ? g_strdup_printf ("disc:%d", s->index) : NULL;
}

char *
bro_source_display_name (const BroSource *s)
{
  if (s->kind == BRO_SOURCE_DRIVE)
    return *s->path ? g_strdup (s->path) : g_strdup_printf ("Drive %d", s->index);
  return g_path_get_basename (s->path);
}

/* ---- settings.conf ---- */

GHashTable *
bro_settings_conf_parse (const char *text)
{
  GHashTable *t = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, g_free);
  g_auto (GStrv) lines = g_strsplit (text ? text : "", "\n", -1);
  for (int i = 0; lines[i]; i++)
    {
      char *l = g_strstrip (lines[i]);
      char *eq;
      if (!*l || *l == '#' || !(eq = strchr (l, '=')))
        continue;
      *eq = '\0';
      g_autofree char *key = g_strstrip (g_strdup (l));
      g_autofree char *value = g_strstrip (g_strdup (eq + 1));
      size_t n = strlen (value);
      if (n >= 2 && value[0] == '"' && value[n - 1] == '"')
        {
          value[n - 1] = '\0';
          memmove (value, value + 1, n - 1);
        }
      if (*key)
        g_hash_table_replace (t, g_steal_pointer (&key), g_steal_pointer (&value));
    }
  return t;
}

char *
bro_settings_conf_serialize (GHashTable *settings, const char *header)
{
  GString *s = g_string_new (NULL);
  g_autoptr (GList) keys = g_list_sort (g_hash_table_get_keys (settings), (GCompareFunc) strcmp);
  g_string_append_printf (s, "#\n# MakeMKV settings file. %s.\n# Changes made here are overwritten before every job.\n#\n\n",
                          header ? header : "Written by Bromelia");
  for (GList *l = keys; l; l = l->next)
    {
      g_autofree char *v = g_strdup (g_hash_table_lookup (settings, l->data));
      g_strdelimit (v, "\"", '\'');
      g_strdelimit (v, "\n", ' ');
      g_string_append_printf (s, "%s = \"%s\"\n", (char *) l->data, v);
    }
  return g_string_free (s, FALSE);
}

static char *
xml_escape (const char *s)
{
  return g_markup_escape_text (s ? s : "", -1);
}

char *
bro_profile_build (const BroGeneratedProfile *p, const char *selection_override)
{
  const char *rule = selection_override ? selection_override
                     : (p->selection_rule && *p->selection_rule ? p->selection_rule : BRO_DEFAULT_SELECTION);
  g_autofree char *name = xml_escape (p->name);
  g_autofree char *rule_x = xml_escape (rule);
#define TF(v) ((v) ? "true" : "false")
  return g_strdup_printf (
    "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
    "<!-- Generated by Bromelia. Edit the drive configuration instead of this file. -->\n"
    "<profile>\n"
    "    <name lang=\"eng\">%s</name>\n\n"
    "    <mkvSettings\n"
    "        ignoreForcedSubtitlesFlag=\"%s\"\n"
    "        useISO639Type2T=\"%s\"\n"
    "        setFirstAudioTrackAsDefault=\"%s\"\n"
    "        setFirstSubtitleTrackAsDefault=\"%s\"\n"
    "        setFirstForcedSubtitleTrackAsDefault=\"%s\"\n"
    "        insertFirstChapter00IfMissing=\"%s\"\n"
    "    />\n\n"
    "    <profileSettings\n"
    "        app_DefaultSelectionString=\"%s\"\n"
    "    />\n\n"
    "    <outputSettings name=\"copy\" outputFormat=\"directCopy\">\n"
    "        <description lang=\"eng\">Copy track as is</description>\n"
    "    </outputSettings>\n\n"
    "    <outputSettings name=\"lpcm\" outputFormat=\"LPCM-raw\">\n"
    "        <description lang=\"eng\">Save as raw LPCM</description>\n"
    "    </outputSettings>\n\n"
    "    <outputSettings name=\"wavex\" outputFormat=\"LPCM-wavex\">\n"
    "        <description lang=\"eng\">Save as LPCM in WAV container</description>\n"
    "    </outputSettings>\n\n"
    "    <outputSettings name=\"flac-best\" outputFormat=\"FLAC\">\n"
    "        <description lang=\"eng\">Save as FLAC (best compression)</description>\n"
    "        <extraArgs>-compression_level 12</extraArgs>\n"
    "    </outputSettings>\n\n"
    "    <outputSettings name=\"flac-fast\" outputFormat=\"FLAC\">\n"
    "        <description lang=\"eng\">Save as FLAC (fast compression)</description>\n"
    "        <extraArgs>-compression_level 5</extraArgs>\n"
    "    </outputSettings>\n\n"
    "    <trackSettings input=\"default\">\n"
    "        <output outputSettingsName=\"copy\"\n"
    "                defaultSelection=\"$app_DefaultSelectionString\">\n"
    "        </output>\n"
    "    </trackSettings>\n\n"
    "    <trackSettings input=\"LPCM-stereo\">\n"
    "        <output outputSettingsName=\"%s\"\n"
    "                defaultSelection=\"$app_DefaultSelectionString\">\n"
    "        </output>\n"
    "    </trackSettings>\n\n"
    "    <trackSettings input=\"LPCM-multi\">\n"
    "        <output outputSettingsName=\"%s\"\n"
    "                defaultSelection=\"$app_DefaultSelectionString\">\n"
    "        </output>\n"
    "    </trackSettings>\n"
    "</profile>\n",
    name, TF (p->ignore_forced_subtitles_flag), TF (p->use_iso639_2t), TF (p->set_first_audio_default),
    TF (p->set_first_subtitle_default), TF (p->set_first_forced_subtitle_default), TF (p->insert_first_chapter00),
    rule_x, bro_lpcm_to_string (p->lpcm_stereo), bro_lpcm_to_string (p->lpcm_multichannel));
#undef TF
}

static const char *
settings_subdir (void)
{
#ifdef __APPLE__
  return "Library/MakeMKV";
#else
  return ".MakeMKV";
#endif
}

char *
bro_makemkv_user_folder (void)
{
  return g_build_filename (g_get_home_dir (), settings_subdir (), NULL);
}

GHashTable *
bro_makemkv_installed_settings (void)
{
  g_autofree char *dir = bro_makemkv_user_folder ();
  g_autofree char *file = g_build_filename (dir, "settings.conf", NULL);
  g_autofree char *text = NULL;
  g_file_get_contents (file, &text, NULL, NULL);
  return bro_settings_conf_parse (text);
}

static char *
expand_user (const char *p)
{
  if (p && (g_str_equal (p, "~") || g_str_has_prefix (p, "~/")))
    return g_build_filename (g_get_home_dir (), p + 1, NULL);
  return g_strdup (p ? p : "");
}

BroMakemkvEnv *
bro_makemkv_env_prepare (const char *executable, const BroAppConfig *config, const BroDriveConfig *drive,
                         const char *home, const char *selection_override, GError **error)
{
  BroMakemkvEnv *env = g_new0 (BroMakemkvEnv, 1);
  GHashTable *s = bro_app_config_effective_settings (config, drive);
  const char *dd = g_hash_table_lookup (s, "app_DataDir");
  g_autofree char *settings_dir = g_build_filename (home, settings_subdir (), NULL);
  g_autofree char *header = NULL;
  g_autofree char *conf = NULL;
  g_autofree char *conf_path = NULL;
  GHashTableIter it;
  gpointer k, v;

  env->executable = g_strdup (executable);
  env->home = g_strdup (home);
  g_mkdir_with_parents (settings_dir, 0755);

  /* Share the normal MakeMKV data folder (SDF, keys, KEYDB.cfg) unless configured otherwise. */
  if (!dd || !*dd)
    g_hash_table_replace (s, g_strdup ("app_DataDir"), bro_makemkv_user_folder ());
  else
    g_hash_table_replace (s, g_strdup ("app_DataDir"), expand_user (dd));

  /* Without an explicit key, reuse the one MakeMKV itself is registered with. */
  if (!g_hash_table_lookup (s, "app_Key") || !*(char *) g_hash_table_lookup (s, "app_Key"))
    {
      g_autoptr (GHashTable) installed = bro_makemkv_installed_settings ();
      const char *key = g_hash_table_lookup (installed, "app_Key");
      if (key && *key)
        g_hash_table_replace (s, g_strdup ("app_Key"), g_strdup (key));
    }

  switch (drive->profile.mode)
    {
    case BRO_PROFILE_GENERATED:
      {
        g_autofree char *xml = bro_profile_build (&drive->profile.generated, selection_override);
        env->profile_path = g_build_filename (home, "profile.mmcp.xml", NULL);
        if (!g_file_set_contents (env->profile_path, xml, -1, error))
          {
            g_hash_table_unref (s);
            bro_makemkv_env_free (env);
            return NULL;
          }
        if (selection_override)
          g_hash_table_replace (s, g_strdup ("app_DefaultSelectionString"), g_strdup (selection_override));
        else if (drive->profile.generated.selection_rule && *drive->profile.generated.selection_rule)
          g_hash_table_replace (s, g_strdup ("app_DefaultSelectionString"), g_strdup (drive->profile.generated.selection_rule));
      }
      break;
    case BRO_PROFILE_CUSTOM_FILE:
      if (drive->profile.custom_path && *drive->profile.custom_path)
        env->profile_path = expand_user (drive->profile.custom_path);
      /* fall through */
    default:
      if (selection_override)
        g_hash_table_replace (s, g_strdup ("app_DefaultSelectionString"), g_strdup (selection_override));
      break;
    }

  /* Empty values mean "MakeMKV default": leave them out. */
  env->settings = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, g_free);
  g_hash_table_iter_init (&it, s);
  while (g_hash_table_iter_next (&it, &k, &v))
    if (v && *(char *) v)
      g_hash_table_insert (env->settings, g_strdup (k), g_strdup (v));
  g_hash_table_unref (s);

  header = g_strdup_printf ("Drive configuration “%s”", drive->name);
  conf = bro_settings_conf_serialize (env->settings, header);
  conf_path = g_build_filename (settings_dir, "settings.conf", NULL);
  if (!g_file_set_contents (conf_path, conf, -1, error))
    {
      bro_makemkv_env_free (env);
      return NULL;
    }
  return env;
}

void
bro_makemkv_env_free (BroMakemkvEnv *env)
{
  if (!env)
    return;
  g_free (env->executable);
  g_free (env->home);
  g_free (env->profile_path);
  if (env->settings)
    g_hash_table_unref (env->settings);
  g_free (env);
}

char **
bro_makemkv_env_environ (const BroMakemkvEnv *env)
{
  return g_environ_setenv (g_get_environ (), "HOME", env->home, TRUE);
}

GPtrArray *
bro_makemkv_common_args (const BroMakemkvEnv *env, const BroRipConfig *rip)
{
  GPtrArray *a = g_ptr_array_new_with_free_func (g_free);
  g_ptr_array_add (a, g_strdup (env->executable));
  bro_ptr_array_add_all (a, "-r", "--progress=-same", "--messages=-stdout", "--noscan", NULL);
  if (env->profile_path)
    g_ptr_array_add (a, g_strdup_printf ("--profile=%s", env->profile_path));
  if (rip)
    {
      g_autoptr (GPtrArray) extra = NULL;
      if (rip->min_length_seconds >= 0)
        g_ptr_array_add (a, g_strdup_printf ("--minlength=%d", rip->min_length_seconds));
      if (rip->cache_mb > 0)
        g_ptr_array_add (a, g_strdup_printf ("--cache=%d", rip->cache_mb));
      if (rip->direct_io >= 0)
        g_ptr_array_add (a, g_strdup_printf ("--directio=%s", rip->direct_io ? "true" : "false"));
      extra = bro_split_arguments (rip->extra_arguments);
      for (guint i = 0; i < extra->len; i++)
        g_ptr_array_add (a, g_strdup (extra->pdata[i]));
    }
  return a;
}

GPtrArray *
bro_makemkv_info_args (const BroMakemkvEnv *env, const BroSource *src, const BroRipConfig *rip)
{
  GPtrArray *a = bro_makemkv_common_args (env, rip);
  g_ptr_array_add (a, g_strdup ("info"));
  g_ptr_array_add (a, bro_source_info_argument (src));
  return a;
}

GPtrArray *
bro_makemkv_mkv_args (const BroMakemkvEnv *env, const BroSource *src, const char *title, const char *dest, const BroRipConfig *rip)
{
  GPtrArray *a = bro_makemkv_common_args (env, rip);
  g_ptr_array_add (a, g_strdup ("mkv"));
  g_ptr_array_add (a, bro_source_info_argument (src));
  g_ptr_array_add (a, g_strdup (title));
  g_ptr_array_add (a, g_strdup (dest));
  return a;
}

GPtrArray *
bro_makemkv_backup_args (const BroMakemkvEnv *env, const BroSource *src, gboolean decrypt, const char *dest, const BroRipConfig *rip)
{
  char *disc = bro_source_backup_argument (src);
  GPtrArray *a;
  if (!disc)
    return NULL;
  a = bro_makemkv_common_args (env, rip);
  g_ptr_array_add (a, g_strdup ("backup"));
  if (decrypt)
    g_ptr_array_add (a, g_strdup ("--decrypt"));
  g_ptr_array_add (a, disc);
  g_ptr_array_add (a, g_strdup (dest));
  return a;
}

GPtrArray *
bro_makemkv_scan_args (void)
{
  GPtrArray *a = g_ptr_array_new_with_free_func (g_free);
  bro_ptr_array_add_all (a, "-r", "--cache=1", "--progress=-same", "--messages=-stdout", "info", "disc:9999", NULL);
  return a;
}

char *
bro_find_tool (const char *configured, const char *name)
{
  g_autofree char *c = expand_user (configured);
  static const char *const extra_dirs[] = {
    "/usr/bin", "/usr/local/bin", "/opt/makemkv/bin", "/app/bin", "/opt/homebrew/bin",
    "/Applications/MakeMKV.app/Contents/MacOS", NULL
  };
  if (*c)
    return g_file_test (c, G_FILE_TEST_IS_EXECUTABLE) ? g_steal_pointer (&c) : NULL;
  char *found = g_find_program_in_path (name);
  if (found)
    return found;
  for (int i = 0; extra_dirs[i]; i++)
    {
      char *p = g_build_filename (extra_dirs[i], name, NULL);
      if (g_file_test (p, G_FILE_TEST_IS_EXECUTABLE))
        return p;
      g_free (p);
    }
  return NULL;
}

/* ---- catalog ---- */

static void
catalog_setting_free (BroCatalogSetting *s)
{
  g_free (s->key);
  g_free (s->label);
  g_free (s->type);
  g_free (s->def);
  g_free (s->help);
  if (s->choice_values) g_ptr_array_unref (s->choice_values);
  if (s->choice_labels) g_ptr_array_unref (s->choice_labels);
  g_free (s);
}

static void
catalog_section_free (BroCatalogSection *s)
{
  g_free (s->id);
  g_free (s->title);
  g_ptr_array_unref (s->settings);
  g_free (s);
}

static char *
obj_str (JsonObject *o, const char *k)
{
  JsonNode *n = json_object_get_member (o, k);
  return (n && JSON_NODE_HOLDS_VALUE (n) && json_node_get_value_type (n) == G_TYPE_STRING) ? g_strdup (json_node_get_string (n)) : NULL;
}

BroCatalog *
bro_catalog_load_from_data (const char *json, GError **error)
{
  g_autoptr (JsonParser) parser = json_parser_new ();
  BroCatalog *c;
  JsonObject *root;
  JsonArray *sections, *arr;

  if (!json_parser_load_from_data (parser, json, -1, error))
    return NULL;
  root = json_node_get_object (json_parser_get_root (parser));
  c = g_new0 (BroCatalog, 1);
  c->sections = g_ptr_array_new_with_free_func ((GDestroyNotify) catalog_section_free);
  c->token_names = g_ptr_array_new_with_free_func (g_free);
  c->token_helps = g_ptr_array_new_with_free_func (g_free);
  c->preset_names = g_ptr_array_new_with_free_func (g_free);
  c->preset_rules = g_ptr_array_new_with_free_func (g_free);

  sections = json_object_get_array_member (root, "sections");
  for (guint i = 0; sections && i < json_array_get_length (sections); i++)
    {
      JsonObject *so = json_array_get_object_element (sections, i);
      BroCatalogSection *sec = g_new0 (BroCatalogSection, 1);
      JsonArray *settings = json_object_get_array_member (so, "settings");
      sec->id = obj_str (so, "id");
      sec->title = obj_str (so, "title");
      sec->settings = g_ptr_array_new_with_free_func ((GDestroyNotify) catalog_setting_free);
      for (guint j = 0; settings && j < json_array_get_length (settings); j++)
        {
          JsonObject *o = json_array_get_object_element (settings, j);
          BroCatalogSetting *s = g_new0 (BroCatalogSetting, 1);
          s->key = obj_str (o, "key");
          s->label = obj_str (o, "label");
          s->type = obj_str (o, "type");
          s->def = obj_str (o, "default");
          s->help = obj_str (o, "help");
          s->advanced = json_object_has_member (o, "advanced") && json_object_get_boolean_member (o, "advanced");
          s->this_platform = TRUE;
          if (json_object_has_member (o, "platforms"))
            {
              JsonArray *pl = json_object_get_array_member (o, "platforms");
              s->this_platform = FALSE;
              for (guint k = 0; k < json_array_get_length (pl); k++)
                if (g_str_equal (json_array_get_string_element (pl, k), "linux"))
                  s->this_platform = TRUE;
            }
          if (json_object_has_member (o, "choices"))
            {
              JsonArray *ch = json_object_get_array_member (o, "choices");
              s->choice_values = g_ptr_array_new_with_free_func (g_free);
              s->choice_labels = g_ptr_array_new_with_free_func (g_free);
              for (guint k = 0; k < json_array_get_length (ch); k++)
                {
                  JsonObject *co = json_array_get_object_element (ch, k);
                  g_ptr_array_add (s->choice_values, obj_str (co, "value"));
                  g_ptr_array_add (s->choice_labels, obj_str (co, "label"));
                }
            }
          g_ptr_array_add (sec->settings, s);
        }
      g_ptr_array_add (c->sections, sec);
    }
  arr = json_object_has_member (root, "selectionTokens") ? json_object_get_array_member (root, "selectionTokens") : NULL;
  for (guint i = 0; arr && i < json_array_get_length (arr); i++)
    {
      JsonObject *o = json_array_get_object_element (arr, i);
      g_ptr_array_add (c->token_names, obj_str (o, "token"));
      g_ptr_array_add (c->token_helps, obj_str (o, "help"));
    }
  arr = json_object_has_member (root, "selectionPresets") ? json_object_get_array_member (root, "selectionPresets") : NULL;
  for (guint i = 0; arr && i < json_array_get_length (arr); i++)
    {
      JsonObject *o = json_array_get_object_element (arr, i);
      g_ptr_array_add (c->preset_names, obj_str (o, "name"));
      g_ptr_array_add (c->preset_rules, obj_str (o, "rule"));
    }
  return c;
}

BroCatalog *
bro_catalog_get (void)
{
  static BroCatalog *cached;
  if (g_once_init_enter (&cached))
    {
      g_autoptr (GBytes) bytes = g_resources_lookup_data ("/app/bromelia/Bromelia/settings-catalog.json", 0, NULL);
      BroCatalog *c = NULL;
      if (bytes)
        {
          g_autofree char *text = g_strndup (g_bytes_get_data (bytes, NULL), g_bytes_get_size (bytes));
          c = bro_catalog_load_from_data (text, NULL);
        }
      if (!c)
        c = bro_catalog_load_from_data ("{\"sections\":[]}", NULL);
      g_once_init_leave (&cached, c);
    }
  return cached;
}

gboolean
bro_catalog_has_key (BroCatalog *c, const char *key)
{
  for (guint i = 0; i < c->sections->len; i++)
    {
      BroCatalogSection *sec = c->sections->pdata[i];
      for (guint j = 0; j < sec->settings->len; j++)
        if (g_str_equal (((BroCatalogSetting *) sec->settings->pdata[j])->key, key))
          return TRUE;
    }
  return FALSE;
}

GPtrArray *
bro_catalog_keys (BroCatalog *c)
{
  GPtrArray *a = g_ptr_array_new_with_free_func (g_free);
  for (guint i = 0; i < c->sections->len; i++)
    {
      BroCatalogSection *sec = c->sections->pdata[i];
      for (guint j = 0; j < sec->settings->len; j++)
        g_ptr_array_add (a, g_strdup (((BroCatalogSetting *) sec->settings->pdata[j])->key));
    }
  return a;
}

/* ---- process runner ---- */

typedef struct {
  GSubprocess *proc;
  GPid pid;
  GMutex lock;
  GCond cond;
  gboolean finished;       /* the reading thread is done */
  gboolean cancelled;      /* the caller's cancellable fired */
  gboolean timed_out, stalled, abandoned;
  gboolean stopped;        /* the watchdog started stopping it */
  BroRunOptions opt;
  gint64 last_output;      /* monotonic */
  GCancellable *read_cancel;  /* stops reading output */
  GCancellable *wait_cancel;  /* stops waiting for the process (abandoned) */
} RunState;

static gboolean
process_gone (RunState *st)
{
#ifdef G_OS_UNIX
  return st->pid > 0 && kill (st->pid, 0) != 0 && errno == ESRCH;
#else
  return FALSE;
#endif
}

/* Sends @sig to the process's group: the tool and whatever it started (each tool leads a process group of its own,
 * tool_child_setup), as a shell's background child would otherwise be left running. */
static void
signal_group (RunState *st, int sig)
{
#ifdef G_OS_UNIX
  if (st->pid > 0 && kill (-st->pid, sig) == 0)
    return;
  g_subprocess_send_signal (st->proc, sig);
#else
  g_subprocess_force_exit (st->proc);
#endif
}

/* Watches one process: the overall timeout, output stalls, cancellation (stop signal, then SIGKILL after 5 s, to the
 * process's whole group), a process that ended but whose output pipe stays open (a child it left behind: stop reading
 * after 5 s), and a process that doesn't die even after SIGKILL (stuck in the kernel on a hung drive: abandoned after
 * 30 s). */
static gpointer
watchdog_thread (gpointer data)
{
  RunState *st = data;
  gint64 start = g_get_monotonic_time (), stop_at = 0, killed_at = 0, gone_at = 0;
  g_mutex_lock (&st->lock);
  while (!st->finished)
    {
      gint64 now = g_get_monotonic_time ();
      gboolean stop = FALSE, gone = process_gone (st);
      /* Only a process that is still running is stopped: once it has ended, what it left running (holding the output
       * pipe) is left alone, and reading just ends 5 s later. */
      if (gone && !stop_at)
        stop_at = killed_at = -1;
      if (!stop_at && st->opt.timeout_seconds > 0 && now - start >= (gint64) st->opt.timeout_seconds * G_USEC_PER_SEC)
        {
          st->timed_out = st->stopped = TRUE;
          signal_group (st, SIGKILL);
          stop_at = killed_at = now;
        }
      if (!stop_at && st->opt.stall_seconds > 0 && now - st->last_output >= (gint64) st->opt.stall_seconds * G_USEC_PER_SEC)
        st->stalled = stop = TRUE;
      if (!stop_at && st->cancelled)
        stop = TRUE;
      if (stop)
        {
          st->stopped = TRUE;
#ifdef G_OS_UNIX
          signal_group (st, st->opt.stop_signal > 0 ? st->opt.stop_signal : SIGINT);
#else
          g_subprocess_force_exit (st->proc);
          killed_at = now;
#endif
          stop_at = now;
        }
      if (stop_at > 0 && !killed_at && now - stop_at >= 5 * G_USEC_PER_SEC)
        {
          signal_group (st, SIGKILL);
          killed_at = now;
        }
      if (killed_at > 0 && !gone && now - killed_at >= 30 * G_USEC_PER_SEC)
        {
          st->abandoned = TRUE;
          g_cancellable_cancel (st->read_cancel);
          g_cancellable_cancel (st->wait_cancel);
          break;
        }
      if (!gone_at && gone)
        gone_at = now;
      if (gone_at && now - gone_at >= 5 * G_USEC_PER_SEC)
        g_cancellable_cancel (st->read_cancel);
      g_cond_wait_until (&st->cond, &st->lock, now + G_USEC_PER_SEC / 4);
    }
  g_mutex_unlock (&st->lock);
  return NULL;
}

#ifdef G_OS_UNIX
/* So that a crash (or kill -9) of Bromelia leaves no tools behind, each process gets a watcher: /bin/sh in its own
 * process group, reading a pipe that nothing writes to. Bromelia holds the pipe's write end (close-on-exec, never
 * closed); when Bromelia ends, however it ends, the kernel closes it, the watcher's read returns, and it stops the
 * process's group: TERM, then KILL if the group is still there 5 s later. The watcher stops as soon as the group is
 * gone, so it never signals one used again. When the process ends first, its watcher is killed and reaped at once.
 * (makemkvcon ignores SIGPIPE, so without this it went on reading the disc into a folder recovery had marked
 * INCOMPLETE.) GSubprocess reaps the process just before the wait returns, so for that moment a watcher outlives it;
 * Bromelia would have to die in that moment, and the pid be reused, for a stray signal. No PR_SET_PDEATHSIG: it fires
 * when the thread that started the child ends. */
static const char lifeline_script[] = "read -r _; kill -s TERM -- \"-$1\" 2>/dev/null || exit 0; i=0; while [ $i -lt 50 ]; do sleep 0.1; "
                                      "kill -0 -- \"-$1\" 2>/dev/null || exit 0; i=$((i+1)); done; kill -s KILL -- \"-$1\" 2>/dev/null";

/* In the tool, before exec: a process group of its own, so that stopping it reaches what it starts too, and a
 * terminal's ^C reaches Bromelia, which stops its jobs, rather than the tools directly. */
static void
tool_child_setup (gpointer data)
{
  setpgid (0, 0);
}

static void
lifeline_child_setup (gpointer data)
{
  sigset_t none;
  setpgid (0, 0); /* out of Bromelia's group: a terminal's ^C doesn't reach it */
  sigemptyset (&none);
  sigprocmask (SIG_SETMASK, &none, NULL);
}

/* The pipe's read end; -1 when it couldn't be made. */
static int
lifeline_read_end (void)
{
  static gsize once;
  static int read_end = -1;
  if (g_once_init_enter (&once))
    {
      int fds[2];
      if (g_unix_open_pipe (fds, FD_CLOEXEC, NULL))
        read_end = fds[0]; /* fds[1] stays open until Bromelia ends */
      g_once_init_leave (&once, 1);
    }
  return read_end;
}

GPid
bro_lifeline_watch (GPid pid, int read_end)
{
  g_autofree char *arg = g_strdup_printf ("%d", (int) pid);
  const char *argv[] = { "/bin/sh", "-c", lifeline_script, "bromelia-lifeline", arg, NULL };
  const char *envp[] = { "PATH=/usr/bin:/bin", NULL };
  GPid watcher = 0;
  if (read_end < 0)
    read_end = lifeline_read_end ();
  if (pid <= 0 || read_end < 0)
    return 0;
  if (!g_spawn_async_with_pipes_and_fds (NULL, argv, envp,
                                         G_SPAWN_DO_NOT_REAP_CHILD | G_SPAWN_STDOUT_TO_DEV_NULL | G_SPAWN_STDERR_TO_DEV_NULL,
                                         lifeline_child_setup, NULL, read_end, -1, -1, NULL, NULL, 0, &watcher, NULL, NULL, NULL, NULL))
    return 0;
  return watcher;
}

void
bro_lifeline_end (GPid watcher)
{
  int status;
  if (watcher <= 0)
    return;
  kill (watcher, SIGKILL);
  while (waitpid (watcher, &status, 0) == -1 && errno == EINTR)
    ;
}

typedef struct {
  GSubprocess *proc;
  GPid watcher;
} Abandoned;

/* An abandoned process keeps its watcher until it ends, if it ever does. */
static gpointer
end_lifeline_when_gone (gpointer data)
{
  Abandoned *a = data;
  g_subprocess_wait (a->proc, NULL, NULL);
  bro_lifeline_end (a->watcher);
  g_object_unref (a->proc);
  g_free (a);
  return NULL;
}
#endif

static void
on_cancelled (GCancellable *c, gpointer data)
{
  RunState *st = data;
  g_mutex_lock (&st->lock);
  st->cancelled = TRUE;
  g_cond_signal (&st->cond);
  g_mutex_unlock (&st->lock);
}

gboolean
bro_process_run (const char *const *argv, const char *const *envp, const char *cwd, int timeout_seconds,
                 GCancellable *cancellable, BroLineFunc func, gpointer user_data,
                 int *exit_status, gboolean *was_cancelled, gboolean *timed_out, GError **error)
{
  BroRunOptions opt = { timeout_seconds, 0, 0 };
  BroRunStatus st = { 0 };
  gboolean ok = bro_process_run_ex (argv, envp, cwd, &opt, cancellable, func, user_data, &st, error);
  if (exit_status)
    *exit_status = st.exit_status;
  if (was_cancelled)
    *was_cancelled = st.cancelled;
  if (timed_out)
    *timed_out = st.timed_out;
  return ok;
}

gboolean
bro_process_run_ex (const char *const *argv, const char *const *envp, const char *cwd, const BroRunOptions *opt,
                    GCancellable *cancellable, BroLineFunc func, gpointer user_data, BroRunStatus *out, GError **error)
{
  g_autoptr (GSubprocessLauncher) launcher = g_subprocess_launcher_new (G_SUBPROCESS_FLAGS_STDOUT_PIPE | G_SUBPROCESS_FLAGS_STDERR_MERGE |
                                                                        G_SUBPROCESS_FLAGS_STDIN_INHERIT);
  g_autoptr (GDataInputStream) data = NULL;
  RunState st = { 0 };
  GThread *watchdog;
  gulong handler = 0;
  gboolean waited;
  GPid watcher = 0;
  char *line;

  if (out)
    memset (out, 0, sizeof *out);
  if (envp)
    g_subprocess_launcher_set_environ (launcher, (char **) envp);
  if (cwd && g_file_test (cwd, G_FILE_TEST_IS_DIR))
    g_subprocess_launcher_set_cwd (launcher, cwd);
#ifdef G_OS_UNIX
  g_subprocess_launcher_set_child_setup (launcher, tool_child_setup, NULL, NULL);
#endif
  if (g_cancellable_is_cancelled (cancellable))
    {
      if (out)
        out->cancelled = TRUE;
      g_set_error_literal (error, G_IO_ERROR, G_IO_ERROR_CANCELLED, "Cancelled");
      return FALSE;
    }

  st.proc = g_subprocess_launcher_spawnv (launcher, argv, error);
  if (!st.proc)
    return FALSE;
  if (g_subprocess_get_identifier (st.proc))
    st.pid = (GPid) atoi (g_subprocess_get_identifier (st.proc));
#ifdef G_OS_UNIX
  watcher = bro_lifeline_watch (st.pid, -1);
#endif
  g_mutex_init (&st.lock);
  g_cond_init (&st.cond);
  if (opt)
    st.opt = *opt;
  st.last_output = g_get_monotonic_time ();
  st.read_cancel = g_cancellable_new ();
  st.wait_cancel = g_cancellable_new ();
  if (cancellable)
    handler = g_cancellable_connect (cancellable, G_CALLBACK (on_cancelled), &st, NULL);
  watchdog = g_thread_new ("bro-watchdog", watchdog_thread, &st);

  data = g_data_input_stream_new (g_subprocess_get_stdout_pipe (st.proc));
  g_data_input_stream_set_newline_type (data, G_DATA_STREAM_NEWLINE_TYPE_ANY);
  while ((line = g_data_input_stream_read_line (data, NULL, st.read_cancel, NULL)) != NULL)
    {
      g_autofree char *valid = g_utf8_make_valid (line, -1);
      g_mutex_lock (&st.lock);
      st.last_output = g_get_monotonic_time ();
      g_mutex_unlock (&st.lock);
      if (*valid && func)
        func (valid, user_data);
      g_free (line);
    }
  waited = g_subprocess_wait (st.proc, st.wait_cancel, NULL);
#ifdef G_OS_UNIX
  g_mutex_lock (&st.lock);
  if (waited && st.stopped && st.pid > 0)
    kill (-st.pid, SIGKILL); /* what is left of a stopped process's group; a finished one's is left alone */
  g_mutex_unlock (&st.lock);
  if (waited)
    bro_lifeline_end (watcher);
  else if (watcher > 0)
    {
      Abandoned *a = g_new0 (Abandoned, 1);
      a->proc = g_object_ref (st.proc);
      a->watcher = watcher;
      g_thread_unref (g_thread_new ("bro-lifeline", end_lifeline_when_gone, a));
    }
#else
  (void) watcher;
#endif

  g_mutex_lock (&st.lock);
  st.finished = TRUE;
  g_cond_signal (&st.cond);
  g_mutex_unlock (&st.lock);
  g_thread_join (watchdog);
  if (handler)
    g_cancellable_disconnect (cancellable, handler);

  if (out)
    {
      out->exit_status = waited && g_subprocess_get_if_exited (st.proc) ? g_subprocess_get_exit_status (st.proc) : -1;
      out->cancelled = st.cancelled;
      out->timed_out = st.timed_out;
      out->stalled = st.stalled;
      out->abandoned = st.abandoned;
    }
  /* An abandoned process is still running; GSubprocess keeps watching it and reaps it if it ever ends. */
  g_object_unref (st.proc);
  g_object_unref (st.read_cancel);
  g_object_unref (st.wait_cancel);
  g_mutex_clear (&st.lock);
  g_cond_clear (&st.cond);
  return TRUE;
}

/* ---- beta key, sources ---- */

char *
bro_beta_key_parse (const char *html)
{
  g_autoptr (GRegex) code = g_regex_new ("<code>\\s*(T-[A-Za-z0-9@_]{20,})\\s*</code>", 0, 0, NULL);
  g_autoptr (GRegex) any = g_regex_new ("T-[A-Za-z0-9@_]{20,}", 0, 0, NULL);
  g_autoptr (GMatchInfo) m = NULL;
  if (!html)
    return NULL;
  if (g_regex_match (code, html, 0, &m))
    return g_match_info_fetch (m, 1);
  g_clear_pointer (&m, g_match_info_free);
  if (g_regex_match (any, html, 0, &m))
    return g_match_info_fetch (m, 0);
  return NULL;
}

static void
append_line (const char *line, gpointer data)
{
  g_string_append_printf (data, "%s\n", line);
}

char *
bro_beta_key_fetch (GError **error)
{
  g_autofree char *curl = g_find_program_in_path ("curl");
  const char *argv[] = { curl, "-sSL", "--max-time", "30", BRO_BETA_KEY_URL, NULL };
  g_autoptr (GString) page = g_string_new (NULL);
  int status = -1;
  char *key;
  if (!curl)
    {
      g_set_error_literal (error, G_IO_ERROR, G_IO_ERROR_NOT_FOUND, "curl is needed to download the beta key");
      return NULL;
    }
  if (!bro_process_run (argv, NULL, NULL, 60, NULL, append_line, page, &status, NULL, NULL, error))
    return NULL;
  key = status == 0 ? bro_beta_key_parse (page->str) : NULL;
  if (!key)
    g_set_error_literal (error, G_IO_ERROR, G_IO_ERROR_FAILED,
                         status == 0 ? "No beta key found on the forum page" : "Could not download the forum page");
  return key;
}

gboolean
bro_beta_key_may_replace (const char *installed)
{
  g_autofree char *k = g_strstrip (g_strdup (installed ? installed : ""));
  return !*k || g_str_has_prefix (k, "T-");
}

BroSource *
bro_source_resolve (const char *path, gboolean is_dir)
{
  static const char *const images[] = { ".iso", ".img", ".udf", NULL };
  static const char *const folders[] = { "BDMV", "VIDEO_TS", "HVDVD_TS", NULL };
  g_autofree char *p = g_strdup (path);
  g_autofree char *dir = NULL;
  size_t n = strlen (p);
  while (n > 1 && p[n - 1] == G_DIR_SEPARATOR)
    p[--n] = '\0';
  if (!is_dir)
    {
      g_autofree char *lower = g_ascii_strdown (p, -1);
      for (int i = 0; images[i]; i++)
        if (g_str_has_suffix (lower, images[i]))
          return bro_source_new_path (BRO_SOURCE_ISO, p);
    }
  /* The folder holding BDMV / VIDEO_TS / HVDVD_TS, looking from the item itself up to three levels. */
  dir = is_dir ? g_strdup (p) : g_path_get_dirname (p);
  for (int level = 0; level < 4 && strlen (dir) > 1; level++)
    {
      g_autofree char *base = g_path_get_basename (dir);
      char *parent = g_path_get_dirname (dir);
      for (int i = 0; folders[i]; i++)
        if (g_ascii_strcasecmp (base, folders[i]) == 0)
          {
            BroSource *s = bro_source_new_path (BRO_SOURCE_FOLDER, parent);
            g_free (parent);
            return s;
          }
      g_free (dir);
      dir = parent;
    }
  return bro_source_new_path (BRO_SOURCE_FOLDER, p);
}
