using System.Collections.Generic;
using Bromelia.Foundation;

namespace Bromelia.Domain;

/// <summary>The MakeMKV conversion profile (.mmcp.xml) Bromelia generates.</summary>
public static class ProfileXml
{
    /// <summary>MakeMKV's own default selection rule, used when the profile has none.</summary>
    public const string MakemkvDefaultSelection =
        "-sel:all,+sel:(favlang|nolang|single),-sel:(havemulti|havecore),-sel:mvcvideo,=100:all,-10:favlang";

    private static string Escape(string s) => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");

    /// <summary>The profile for <paramref name="generated"/> (config-3.json's makemkv.profile.generated; missing
    /// fields take their defaults).</summary>
    public static string Render(JsonValue generated)
    {
        var node = SchemaWalker.Def("MakemkvProfile")["properties"]!["generated"]!;
        var g = SchemaWalker.Normalize(generated, node, "", true, new List<Issue>());
        string B(string key) => g[key]?.AsBool == true ? "true" : "false";
        string S(string key) => g[key]?.AsString ?? "";
        var rule = S("selectionRule").Trim().Length == 0 ? MakemkvDefaultSelection : S("selectionRule");
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
            + "<!-- Generated by Bromelia. Edit the profile in Bromelia instead of this file. -->\n"
            + "<profile>\n"
            + "    <name lang=\"eng\">" + Escape(S("name")) + "</name>\n"
            + "\n"
            + "    <mkvSettings\n"
            + "        ignoreForcedSubtitlesFlag=\"" + B("ignoreForcedSubtitlesFlag") + "\"\n"
            + "        useISO639Type2T=\"" + B("useISO639Type2T") + "\"\n"
            + "        setFirstAudioTrackAsDefault=\"" + B("setFirstAudioTrackAsDefault") + "\"\n"
            + "        setFirstSubtitleTrackAsDefault=\"" + B("setFirstSubtitleTrackAsDefault") + "\"\n"
            + "        setFirstForcedSubtitleTrackAsDefault=\"" + B("setFirstForcedSubtitleTrackAsDefault") + "\"\n"
            + "        insertFirstChapter00IfMissing=\"" + B("insertFirstChapter00IfMissing") + "\"\n"
            + "    />\n"
            + "\n"
            + "    <profileSettings\n"
            + "        app_DefaultSelectionString=\"" + Escape(rule) + "\"\n"
            + "    />\n"
            + "\n"
            + "    <outputSettings name=\"copy\" outputFormat=\"directCopy\">\n"
            + "        <description lang=\"eng\">Copy track as is</description>\n"
            + "    </outputSettings>\n"
            + "\n"
            + "    <outputSettings name=\"lpcm\" outputFormat=\"LPCM-raw\">\n"
            + "        <description lang=\"eng\">Save as raw LPCM</description>\n"
            + "    </outputSettings>\n"
            + "\n"
            + "    <outputSettings name=\"wavex\" outputFormat=\"LPCM-wavex\">\n"
            + "        <description lang=\"eng\">Save as LPCM in WAV container</description>\n"
            + "    </outputSettings>\n"
            + "\n"
            + "    <outputSettings name=\"flac-best\" outputFormat=\"FLAC\">\n"
            + "        <description lang=\"eng\">Save as FLAC (best compression)</description>\n"
            + "        <extraArgs>-compression_level 12</extraArgs>\n"
            + "    </outputSettings>\n"
            + "\n"
            + "    <outputSettings name=\"flac-fast\" outputFormat=\"FLAC\">\n"
            + "        <description lang=\"eng\">Save as FLAC (fast compression)</description>\n"
            + "        <extraArgs>-compression_level 5</extraArgs>\n"
            + "    </outputSettings>\n"
            + "\n"
            + Track("default", "copy")
            + "\n"
            + Track("LPCM-stereo", S("lpcmStereo"))
            + "\n"
            + Track("LPCM-multi", S("lpcmMultichannel"))
            + "</profile>\n";
    }

    private static string Track(string input, string output) =>
        "    <trackSettings input=\"" + input + "\">\n"
        + "        <output outputSettingsName=\"" + Escape(output) + "\"\n"
        + "                defaultSelection=\"$app_DefaultSelectionString\">\n"
        + "        </output>\n"
        + "    </trackSettings>\n";
}
