#!/usr/bin/env python3
"""Embeds the database migrations in each platform's Adapters (rearchitecture plan §10.4, §23).

SqliteStore runs shared/schema/db/NNNN_*.sql verbatim, in order, each in one transaction, when PRAGMA user_version
is below NNNN. SwiftPM can't bundle files from outside a target, so the files are compiled in, the same way on all
three platforms (the text is unchanged, comments included).

  Swift  macos/BromeliaKit/Sources/BroAdapters/Store/Migrations.swift   enum Migrations (internal)
  C#     windows/src/Bromelia.Adapters/Store/Migrations.cs              class Migrations (internal)
  C      linux/src/adapters/store/bro-migrations.c                      _bro_migrations ()

Usage: tools/gen-migrations.py [--check]   (--check: fail when a generated file is stale; CI runs it)
Needs only the Python 3 standard library.
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / "shared" / "schema" / "db"
HEADER = "Generated by tools/gen-migrations.py from the .sql files of shared/schema/db. Don't edit."


def migrations():
    out = []
    for p in sorted(DB.glob("*.sql")):
        m = re.match(r"(\d{4})_", p.name)
        if not m:
            continue
        out.append((int(m.group(1)), p.name, p.read_text(encoding="utf-8")))
    versions = [v for v, _, _ in out]
    if versions != list(range(1, len(out) + 1)):
        raise SystemExit(f"gen-migrations: migrations must be numbered 1, 2, … without gaps; found {versions}")
    return out


def lines(text):
    return text.split("\n")


def swift(ms):
    body = []
    for version, name, text in ms:
        if '"##' in text:
            raise SystemExit(f"gen-migrations: {name} can't be a Swift raw string")
        parts = "\n".join(f'            ##"{l}"##,' for l in lines(text))
        body.append(f"        (version: {version}, name: \"{name}\", sql: [\n{parts}\n        ].joined(separator: \"\\n\")),")
    return (f"// {HEADER}\n\n/// The migrations of shared/schema/db, in order, compiled in.\nenum Migrations {{\n"
            f"    static let all: [(version: Int, name: String, sql: String)] = [\n" + "\n".join(body) + "\n    ]\n}\n")


def cs(ms):
    body = []
    for version, name, text in ms:
        parts = "\n".join(f"            + {json.dumps(l + chr(10), ensure_ascii=False)}" for l in lines(text)[:-1]) or ""
        last = lines(text)[-1]
        parts += f"\n            + {json.dumps(last, ensure_ascii=False)}"
        body.append(f"        ({version}, \"{name}\", \"\"\n{parts}),")
    return (f"// {HEADER}\n\nnamespace Bromelia.Adapters;\n\n/// <summary>The migrations of shared/schema/db, in order, compiled in.</summary>\n"
            f"internal static class Migrations\n{{\n    public static readonly (int Version, string Name, string Sql)[] All =\n    {{\n"
            + "\n".join(body) + "\n    };\n}\n")


def c_source(ms):
    texts, entries = [], []
    for i, (version, name, text) in enumerate(ms):
        parts = "\n".join(f"  {json.dumps(l + chr(10), ensure_ascii=False)}" for l in lines(text)[:-1])
        parts += f"\n  {json.dumps(lines(text)[-1], ensure_ascii=False)}"
        texts.append(f"static const char sql_{i}[] =\n{parts};\n")
        entries.append(f"  {{ {version}, \"{name}\", sql_{i} }},")
    return (f"/* {HEADER} */\n#include \"bro-migrations.h\"\n\n" + "\n".join(texts)
            + f"\nstatic const BroMigration all[] = {{\n" + "\n".join(entries) + "\n  { 0, NULL, NULL },\n};\n\n"
            "const BroMigration *\n_bro_migrations (void)\n{\n  return all;\n}\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    ms = migrations()
    outputs = {
        ROOT / "macos/BromeliaKit/Sources/BroAdapters/Store/Migrations.swift": swift(ms),
        ROOT / "windows/src/Bromelia.Adapters/Store/Migrations.cs": cs(ms),
        ROOT / "linux/src/adapters/store/bro-migrations.c": c_source(ms),
    }
    stale = []
    for path, content in outputs.items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    for s in stale:
        print(f"gen-migrations: {s} is stale; run tools/gen-migrations.py")
    print(f"gen-migrations: {len(ms)} migration(s); {len(stale)} stale file(s)")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
