#!/usr/bin/env python3
"""Generates the MessageCode enum of each platform from shared/messages/codes.json (rearchitecture plan §16).

  Swift  macos/BromeliaKit/Sources/BroDomain/Messages/MessageCode.swift   enum MessageCode: String
  C#     windows/src/Bromelia.Domain/Messages/MessageCode.cs              record struct MessageCode, one field per code
  C      linux/src/domain/messages/bro-message-code.{h,c}                 BroMessageCode + wire forms

The wire form is the code itself ("rip.readErrors"); the names follow §5.2: ripReadErrors, RipReadErrors,
BRO_MSG_RIP_READ_ERRORS. Codes keep the order of codes.json.

Usage: tools/gen-messages.py [--check]   (--check: fail when a generated file is stale; CI runs it)
Needs only the Python 3 standard library.
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CODES = ROOT / "shared" / "messages" / "codes.json"
HEADER = "Generated by tools/gen-messages.py from shared/messages/codes.json. Don't edit."


def camel(code):
    parts = code.split(".")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def upper_snake(code):
    name = camel(code)
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", "_", name).upper()


def swift(codes):
    lines = [f"// {HEADER}", "", "/// Every message and error code the engine emits (plan §16). The raw value is the wire form.",
             "public enum MessageCode: String, Sendable, CaseIterable {"]
    lines += [f"    case {camel(c)} = \"{c}\"" for c in codes]
    lines += ["", "    /// The wire form: `rip.readErrors`.",
              "    public static func wire(_ code: MessageCode) -> String { code.rawValue }", "",
              "    /// The code for a wire form; nil when it isn't one.",
              "    public static func parse(_ text: String) -> MessageCode? { MessageCode(rawValue: text) }", "}", ""]
    return "\n".join(lines)


def cs(codes):
    lines = [f"// {HEADER}", "", "namespace Bromelia.Domain;", "",
             "/// <summary>Every message and error code the engine emits (plan §16). The wire form is the code text", "/// (<c>rip.readErrors</c>); <see cref=\"Wire\"/> and <see cref=\"Parse\"/> convert.</summary>",
             "public readonly record struct MessageCode", "{",
             "    private readonly int _index;", "",
             "    private MessageCode(int index) { _index = index; }", ""]
    for i, c in enumerate(codes):
        lines.append(f"    public static readonly MessageCode {camel(c)[:1].upper() + camel(c)[1:]} = new({i});")
    lines += ["", "    private static readonly string[] Codes =", "    {"]
    lines += [f"        \"{c}\"," for c in codes]
    lines += ["    };", "",
              "    private static readonly System.Collections.Generic.Dictionary<string, int> Index = BuildIndex();", "",
              "    private static System.Collections.Generic.Dictionary<string, int> BuildIndex()", "    {",
              "        var d = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal);",
              "        for (int i = 0; i < Codes.Length; i++) d[Codes[i]] = i;", "        return d;", "    }", "",
              "    /// <summary>Every code, in the order of codes.json.</summary>",
              "    public static System.Collections.Generic.IEnumerable<MessageCode> All()", "    {",
              "        for (int i = 0; i < Codes.Length; i++) yield return new MessageCode(i);", "    }", "",
              "    /// <summary>The wire form: <c>rip.readErrors</c>.</summary>",
              "    public static string Wire(MessageCode code) => Codes[code._index];", "",
              "    /// <summary>The code for a wire form; null when it isn't one.</summary>",
              "    public static MessageCode? Parse(string text) => Index.TryGetValue(text, out var i) ? new MessageCode(i) : null;", "",
              "    public override string ToString() => Codes[_index];", "}", ""]
    return "\n".join(lines)


def c_header(codes):
    lines = [f"/* {HEADER} */", "/* bro-message-code.h: every message and error code the engine emits (plan §16). */", "#pragma once", "",
             "#include <glib.h>", "", "G_BEGIN_DECLS", "", "typedef enum {"]
    lines += [f"  BRO_MSG_{upper_snake(c)}, /* {c} */" for c in codes]
    lines += ["  BRO_MSG_COUNT_", "} BroMessageCode;", "",
              "/* The wire form: \"rip.readErrors\". */", "const char *bro_message_code_wire (BroMessageCode code);", "",
              "/* The code for a wire form; FALSE when it isn't one. */",
              "gboolean bro_message_code_parse (const char *text, BroMessageCode *out);", "", "G_END_DECLS", ""]
    return "\n".join(lines)


def c_source(codes):
    lines = [f"/* {HEADER} */", "#include \"bro-message-code.h\"", "", "#include <string.h>", "",
             "static const char *const codes[BRO_MSG_COUNT_] = {"]
    lines += [f"  \"{c}\"," for c in codes]
    lines += ["};", "", "const char *", "bro_message_code_wire (BroMessageCode code)", "{",
              "  g_return_val_if_fail ((int) code >= 0 && code < BRO_MSG_COUNT_, NULL);", "  return codes[code];", "}", "",
              "gboolean", "bro_message_code_parse (const char *text, BroMessageCode *out)", "{",
              "  for (int i = 0; text && i < BRO_MSG_COUNT_; i++)", "    if (strcmp (codes[i], text) == 0) {",
              "      *out = (BroMessageCode) i;", "      return TRUE;", "    }", "  return FALSE;", "}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    codes = list(json.loads(CODES.read_text(encoding="utf-8"))["codes"])
    if len({camel(c) for c in codes}) != len(codes):
        print("gen-messages: two codes have the same name")
        return 1
    outputs = {
        ROOT / "macos/BromeliaKit/Sources/BroDomain/Messages/MessageCode.swift": swift(codes),
        ROOT / "windows/src/Bromelia.Domain/Messages/MessageCode.cs": cs(codes),
        ROOT / "linux/src/domain/messages/bro-message-code.h": c_header(codes),
        ROOT / "linux/src/domain/messages/bro-message-code.c": c_source(codes),
    }
    stale = []
    for path, text in outputs.items():
        if path.exists() and path.read_text(encoding="utf-8") == text:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    for s in stale:
        print(f"gen-messages: {s} is stale; run tools/gen-messages.py")
    print(f"gen-messages: {len(codes)} codes; {len(stale)} stale file(s)")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
