#!/usr/bin/env python3
"""Embeds the configuration schema in each platform's Domain (rearchitecture plan §24).

ConfigCodec fills defaults, orders keys and drops unknown ones by walking shared/schema/config-3.json, and
ConfigValidator checks values against it. Domain does no I/O, so the schema is compiled in: config-3.json with
common.json's $defs merged into its own (references rewritten to #/$defs/…) and descriptions left out.

  Swift  macos/BromeliaKit/Sources/BroDomain/Config/ConfigSchema.swift   enum ConfigSchema (internal)
  C#     windows/src/Bromelia.Domain/Config/ConfigSchema.cs              class ConfigSchema (internal)
  C      linux/src/domain/config/bro-config-schema.c                     _bro_config_schema_text ()

Usage: tools/gen-config-schema.py [--check]   (--check: fail when a generated file is stale; CI runs it)
Needs only the Python 3 standard library.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "shared" / "schema"
HEADER = "Generated by tools/gen-config-schema.py from shared/schema/config-3.json and common.json. Don't edit."
KEEP = {"type", "properties", "items", "additionalProperties", "default", "enum", "const", "oneOf", "anyOf", "allOf", "$ref",
        "x-inherit", "x-default-background", "required", "minimum", "maximum", "pattern", "propertyNames", "minProperties",
        "not", "if", "then"}


def strip(node):
    if isinstance(node, dict):
        out = {}
        for k, v in node.items():
            if k == "properties":
                out[k] = {name: strip(p) for name, p in v.items()}
            elif k == "default":
                out[k] = v
            elif k in KEEP:
                out[k] = strip(v)
        if "$ref" in out:
            out["$ref"] = "#/$defs/" + out["$ref"].split("/$defs/")[1]
        return out
    if isinstance(node, list):
        return [strip(v) for v in node]
    return node


def bundle():
    config = json.loads((SCHEMA / "config-3.json").read_text(encoding="utf-8"))
    common = json.loads((SCHEMA / "common.json").read_text(encoding="utf-8"))
    defs = {name: strip(d) for name, d in config["$defs"].items()}
    for name, d in common["$defs"].items():
        if name in defs:
            raise SystemExit(f"gen-config-schema: {name} is in both config-3.json and common.json")
        defs[name] = strip(d)
    root = strip({k: v for k, v in config.items() if k != "$defs"})
    root["$defs"] = defs
    return json.dumps(root, separators=(",", ":"), ensure_ascii=False)


def chunks(text, size=100):
    return [text[i:i + size] for i in range(0, len(text), size)]


def swift(text):
    if '"##' in text:
        raise SystemExit("gen-config-schema: the schema text can't be a Swift raw string")
    parts = "\n".join(f'        ##"{c}"##,' for c in chunks(text))
    return (f"// {HEADER}\n\n/// The configuration schema, compiled in (Domain does no I/O).\nenum ConfigSchema {{\n"
            f"    static let text = [\n{parts}\n    ].joined()\n}}\n")


def cs(text):
    parts = "\n".join(f"        + {json.dumps(c, ensure_ascii=False)}" for c in chunks(text))
    return (f"// {HEADER}\n\nnamespace Bromelia.Domain;\n\n/// <summary>The configuration schema, compiled in (Domain does no I/O).</summary>\n"
            f"internal static class ConfigSchema\n{{\n    public const string Text = \"\"\n{parts};\n}}\n")


def c_source(text):
    parts = "\n".join(f"  {json.dumps(c, ensure_ascii=False)}" for c in chunks(text))
    return (f"/* {HEADER} */\n#include \"bro-config-private.h\"\n\nstatic const char text[] =\n{parts};\n\n"
            f"const char *\n_bro_config_schema_text (void)\n{{\n  return text;\n}}\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = bundle()
    if "\"\"\"" in text or "\n" in text:
        raise SystemExit("gen-config-schema: the schema text can't be embedded as is")
    outputs = {
        ROOT / "macos/BromeliaKit/Sources/BroDomain/Config/ConfigSchema.swift": swift(text),
        ROOT / "windows/src/Bromelia.Domain/Config/ConfigSchema.cs": cs(text),
        ROOT / "linux/src/domain/config/bro-config-schema.c": c_source(text),
    }
    stale = []
    for path, content in outputs.items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT))
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    for s in stale:
        print(f"gen-config-schema: {s} is stale; run tools/gen-config-schema.py")
    print(f"gen-config-schema: {len(text)} bytes of schema; {len(stale)} stale file(s)")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
