/* bro-step-kind.h */
#pragma once

#include <glib.h>

G_BEGIN_DECLS

typedef enum {
  BRO_STEP_KIND_AWAIT_MEDIA,
  BRO_STEP_KIND_PROBE,
  BRO_STEP_KIND_RECONCILE,
  BRO_STEP_KIND_READ_NAVIGATION,
  BRO_STEP_KIND_IDENTIFY,
  BRO_STEP_KIND_PLAN,
  BRO_STEP_KIND_DECIDE,
  BRO_STEP_KIND_ACQUIRE,
  BRO_STEP_KIND_RELEASE,
  BRO_STEP_KIND_VERIFY_RIPS,
  BRO_STEP_KIND_TRANSFORM,
  BRO_STEP_KIND_NAME,
  BRO_STEP_KIND_SEAL,
  BRO_STEP_KIND_COMMIT,
  BRO_STEP_KIND_PUBLISH,
  BRO_STEP_KIND_PROTECT,
  BRO_STEP_KIND_POST_PROCESS,
  BRO_STEP_KIND_NOTIFY,
  BRO_STEP_KIND_RIP_AUDIO,
  BRO_STEP_KIND_IMAGE_DATA,
  BRO_STEP_KIND_MERGE_ATTEMPTS,
  BRO_STEP_KIND_VERIFY_UNIT,
  BRO_STEP_KIND_REPLICATE,
  BRO_STEP_KIND_PARITY,
  BRO_STEP_KIND_REPAIR,
  BRO_STEP_KIND_RESCAN,
  BRO_STEP_KIND_RUN_COMMAND,
  BRO_STEP_KIND_TRANSCODE,
} BroStepKind;

/* The wire form ("awaitMedia"), as in shared/schema/common.json. */
const char *bro_step_kind_to_wire (BroStepKind value);
gboolean bro_step_kind_from_wire (const char *text, BroStepKind *out);

G_END_DECLS
